/**
 * system-generated-identifiers — regression suite for the app-wide audit:
 * every human-readable business code (Vendor, Medicine, Purchase/PO,
 * Invoice, HMS Request, Stock Adjustment, Expense, Settlement, Return,
 * Petty Cash, Vendor Payment) must be generated by the backend, never typed
 * by a user, unique under concurrency, and never regenerated on edit.
 *
 * Run with: npx tsx scripts/test-system-generated-codes.ts
 */
import { PrismaClient } from '@prisma/client';

const API_BASE = 'http://localhost:4100/api/v1';
const CREDENTIALS = { identifier: 'superadmin', password: 'TestPass@123' };
const TEST_MED_CODES = ['TST-SGC-MED', 'TST-SGC-EXPLICIT'];
const TEST_VENDOR_NAME_PREFIX = 'TST-SGC-Vendor';

let passed = 0;
let failed = 0;
function assert(condition: boolean, message: string) {
  if (condition) { console.log(`  ✅ ${message}`); passed++; }
  else { console.log(`  ❌ ${message}`); failed++; }
}

async function api(method: string, path: string, token: string | null, body?: unknown) {
  const res = await fetch(`${API_BASE}${path}`, {
    method,
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  let json: any;
  try { json = JSON.parse(text); } catch { json = text; }
  return { status: res.status, body: json };
}

const TEST_MED_NAME_PREFIXES = ['Test System Code Medicine', 'Test Explicit Code Medicine', 'Test Concurrent Medicine', 'Test SGC Purchase Medicine'];

async function cleanupMedicines(prisma: PrismaClient, codes: string[]) {
  const meds = await prisma.medicineMaster.findMany({
    where: { OR: [{ code: { in: codes } }, ...TEST_MED_NAME_PREFIXES.map((p) => ({ name: { startsWith: p } }))] },
  });
  for (const med of meds) {
    await prisma.stockLedgerEntry.deleteMany({ where: { medicineId: med.id } });
    await prisma.pharmacyInvoiceLine.deleteMany({ where: { medicineId: med.id } });
    const invoices = await prisma.pharmacyInvoice.findMany({ where: { lines: { some: { medicineId: med.id } } } });
    for (const inv of invoices) {
      await prisma.pharmacyPayment.deleteMany({ where: { invoiceId: inv.id } });
      await prisma.pharmacyInvoiceLine.deleteMany({ where: { invoiceId: inv.id } });
      await prisma.pharmacyInvoice.delete({ where: { id: inv.id } });
    }
    await prisma.purchaseLine.deleteMany({ where: { medicineId: med.id } });
    await prisma.medicineBatch.deleteMany({ where: { medicineId: med.id } });
    await prisma.medicinePackagingLevel.deleteMany({ where: { medicineId: med.id } });
    await prisma.medicineMaster.delete({ where: { id: med.id } });
  }
}

async function cleanupVendors(prisma: PrismaClient) {
  const vendors = await prisma.vendor.findMany({ where: { name: { startsWith: TEST_VENDOR_NAME_PREFIX } } });
  for (const v of vendors) {
    const purchases = await prisma.purchase.findMany({ where: { vendorId: v.id } });
    for (const p of purchases) {
      await prisma.purchaseLine.deleteMany({ where: { purchaseId: p.id } });
      await prisma.purchase.delete({ where: { id: p.id } });
    }
    await prisma.vendorLedgerEntry.deleteMany({ where: { vendorId: v.id } });
    await prisma.vendor.delete({ where: { id: v.id } });
  }
}

async function main() {
  const prisma = new PrismaClient();
  console.log('Cleaning up any leftover test data from a previous run…');
  await cleanupMedicines(prisma, TEST_MED_CODES);
  await cleanupVendors(prisma);

  const login = await api('POST', '/auth/login', null, CREDENTIALS);
  if (login.status !== 200) throw new Error(`Login failed: ${JSON.stringify(login.body)}`);
  const token = login.body.data.accessToken as string;

  const unitsRes = await api('GET', '/units', token);
  const unitsByName = new Map<string, string>(unitsRes.body.data.map((u: any) => [u.name, u.id]));
  const u = (name: string) => unitsByName.get(name)!;

  // ── 1. Vendor Code is never client-supplied ──────────────────────────────
  console.log('\n[1] Vendor Code — system-generated, client value ignored');
  let vendorId = '';
  {
    const preview = await api('GET', '/vendors/next-code', token);
    assert(preview.status === 200 && /^VND-\d{4,}$/.test(preview.body.data.code), `preview endpoint returns a VND-#### code (got "${preview.body?.data?.code}")`);

    // Attempt to smuggle a code in — the schema has no `code` field at all, so this must be silently ignored, not reflected back.
    const r = await api('POST', '/vendors', token, { code: 'HACKED-0001', name: `${TEST_VENDOR_NAME_PREFIX} A`, paymentTermsDays: 15 });
    assert(r.status === 201, `vendor create succeeds (status ${r.status})`);
    assert(/^VND-\d{4,}$/.test(r.body.data.code), `assigned code matches VND-#### format (got "${r.body.data.code}")`);
    assert(r.body.data.code !== 'HACKED-0001', 'client-supplied "code" value was ignored, not assigned');
    vendorId = r.body.data.id;
  }

  // ── 2. Vendor edit never changes the code ────────────────────────────────
  console.log('\n[2] Vendor edit — code never regenerated or changed');
  {
    const before = await prisma.vendor.findUniqueOrThrow({ where: { id: vendorId } });
    const r = await api('PATCH', `/vendors/${vendorId}`, token, { code: 'SHOULD-NOT-APPLY', name: `${TEST_VENDOR_NAME_PREFIX} A Renamed` });
    assert(r.status === 200, `update succeeds (status ${r.status})`);
    const after = await prisma.vendor.findUniqueOrThrow({ where: { id: vendorId } });
    assert(after.code === before.code, `code unchanged after edit (still "${after.code}")`);
    assert(after.name === `${TEST_VENDOR_NAME_PREFIX} A Renamed`, 'name field did update');
  }

  // ── 3. Concurrent vendor creation — no duplicate codes ───────────────────
  console.log('\n[3] Concurrency — 10 simultaneous vendor creates never collide');
  {
    const N = 10;
    const results = await Promise.all(
      Array.from({ length: N }, (_, i) => api('POST', '/vendors', token, { name: `${TEST_VENDOR_NAME_PREFIX} Concurrent ${i}` })),
    );
    const codes = results.map((r) => r.body?.data?.code);
    assert(results.every((r) => r.status === 201), `all ${N} concurrent creates succeeded`);
    assert(new Set(codes).size === N, `all ${N} codes are unique (got: ${codes.join(', ')})`);
    assert(codes.every((c) => /^VND-\d{4,}$/.test(c)), 'every code matches VND-#### format');
  }

  // ── 4. Medicine Code — system-generated by default, override still honored ──
  console.log('\n[4] Medicine Code — auto-generated by default, explicit override still works');
  {
    const preview = await api('GET', '/pharmacy/medicines/next-code', token);
    assert(preview.status === 200 && /^MED-\d{4,}$/.test(preview.body.data.code), `preview endpoint returns a MED-#### code (got "${preview.body?.data?.code}")`);

    const noCode = await api('POST', '/pharmacy/medicines', token, {
      name: 'Test System Code Medicine', baseUnitId: u('Tablet'), baseIsPurchaseUnit: true, baseIsSaleUnit: true, packagingLevels: [],
    });
    assert(noCode.status === 201, `create without code succeeds (status ${noCode.status})`);
    assert(/^MED-\d{4,}$/.test(noCode.body.data.code), `auto-assigned code matches MED-#### (got "${noCode.body.data.code}")`);
    await prisma.medicinePackagingLevel.deleteMany({ where: { medicineId: noCode.body.data.id } });
    await prisma.medicineMaster.delete({ where: { id: noCode.body.data.id } });

    const explicit = await api('POST', '/pharmacy/medicines', token, {
      code: 'TST-SGC-EXPLICIT', name: 'Test Explicit Code Medicine', baseUnitId: u('Tablet'), baseIsPurchaseUnit: true, baseIsSaleUnit: true, packagingLevels: [],
    });
    assert(explicit.status === 201, `create with explicit override code succeeds (status ${explicit.status})`);
    assert(explicit.body.data.code === 'TST-SGC-EXPLICIT', 'authorized override code was honored as-is');
  }

  // ── 5. Medicine edit never regenerates the code ──────────────────────────
  console.log('\n[5] Medicine edit — code never regenerated when omitted from the request');
  {
    const before = await prisma.medicineMaster.findFirstOrThrow({ where: { code: 'TST-SGC-EXPLICIT' } });
    const r = await api('PATCH', `/pharmacy/medicines/${before.id}`, token, { strength: '250mg' });
    assert(r.status === 200, `update succeeds (status ${r.status})`);
    const after = await prisma.medicineMaster.findUniqueOrThrow({ where: { id: before.id } });
    assert(after.code === before.code, `code unchanged after edit (still "${after.code}")`);
    assert(after.strength === '250mg', 'strength field did update');
  }

  // ── 6. Concurrent medicine creation (no explicit code) — no duplicates ───
  console.log('\n[6] Concurrency — 8 simultaneous medicine creates never collide');
  {
    const N = 8;
    const results = await Promise.all(
      Array.from({ length: N }, (_, i) =>
        api('POST', '/pharmacy/medicines', token, { name: `Test Concurrent Medicine ${i}`, baseUnitId: u('Tablet'), baseIsPurchaseUnit: true, baseIsSaleUnit: true, packagingLevels: [] }),
      ),
    );
    const codes = results.map((r) => r.body?.data?.code);
    assert(results.every((r) => r.status === 201), `all ${N} concurrent creates succeeded`);
    assert(new Set(codes).size === N, `all ${N} codes are unique (got: ${codes.join(', ')})`);
    // Clean these up immediately — they're not in TEST_MED_CODES so the final cleanup() wouldn't catch them.
    for (const r of results) {
      if (r.body?.data?.id) {
        await prisma.medicinePackagingLevel.deleteMany({ where: { medicineId: r.body.data.id } }).catch(() => {});
        await prisma.medicineMaster.delete({ where: { id: r.body.data.id } }).catch(() => {});
      }
    }
  }

  // ── 7. Purchase, POS Invoice, Stock Adjustment, Expense, Settlement — clean sequential codes ──
  console.log('\n[7] Purchase / Invoice / Adjustment / Expense / Settlement — clean system codes, not Date.now()');
  {
    const med = await api('POST', '/pharmacy/medicines', token, {
      code: 'TST-SGC-MED', name: 'Test SGC Purchase Medicine', baseUnitId: u('Bottle'), baseIsPurchaseUnit: true, baseIsSaleUnit: true, packagingLevels: [], saleRate: 50,
    });
    const medicineId = med.body.data.id;

    const purchase = await api('POST', '/vendors/purchases', token, {
      vendorId, purchaseDate: new Date().toISOString(),
      lines: [{ medicineId, batchNumber: 'SGC-B1', expiryDate: '2028-01-01', purchaseUnitId: u('Bottle'), purchaseUnitQuantity: 10, unitCost: 40, discountType: 'FLAT', discountValue: 0, taxAmount: 0, freightAmount: 0 }],
      paidNow: 0, post: true,
    });
    assert(purchase.status === 201, `purchase created (status ${purchase.status})`);
    assert(/^PO-\d{4,}$/.test(purchase.body.data.purchaseNumber), `purchaseNumber matches PO-#### (got "${purchase.body.data.purchaseNumber}")`);

    const dispense = await api('POST', '/pharmacy/dispense', token, {
      lines: [{ medicineId, saleUnitQuantity: 1 }], payments: [{ method: 'CASH', amount: 50 }],
    });
    assert(dispense.status === 201, `POS sale created (status ${dispense.status})`);
    assert(/^INV-\d{4,}$/.test(dispense.body.data.invoiceNumber), `invoiceNumber matches INV-#### for a RETAIL sale (got "${dispense.body.data.invoiceNumber}")`);

    const adj = await api('POST', '/pharmacy/stock-adjustments', token, { medicineId, type: 'DAMAGE', quantity: 1, reason: 'TST-SGC damage test' });
    assert(adj.status === 201 || adj.status === 200, `stock adjustment created (status ${adj.status})`);
    assert(/^ADJ-\d{4,}$/.test(adj.body.data.adjustmentNumber), `adjustmentNumber matches ADJ-#### (got "${adj.body.data.adjustmentNumber}")`);

    const exp = await api('POST', '/expenses', token, { category: 'TST-SGC', date: new Date().toISOString(), amount: 500, paymentMethod: 'CASH', description: 'Test expense' });
    assert(exp.status === 201, `expense created (status ${exp.status})`);
    assert(/^EXP-\d{4,}$/.test(exp.body.data.expenseNumber), `expenseNumber matches EXP-#### (got "${exp.body.data.expenseNumber}")`);
    await prisma.cashLedgerEntry.deleteMany({ where: { referenceTable: 'expenses', referenceId: exp.body.data.id } });
    await prisma.expense.delete({ where: { id: exp.body.data.id } });

    const settlement = await api('POST', '/cash/settlements', token, { periodFrom: new Date(Date.now() - 86400000).toISOString(), periodTo: new Date().toISOString(), physicalCash: 0, varianceReason: 'TST-SGC settlement test' });
    assert(settlement.status === 201, `settlement submitted (status ${settlement.status})`);
    assert(/^SET-\d{4,}$/.test(settlement.body.data.settlementNumber), `settlementNumber matches SET-#### (got "${settlement.body.data.settlementNumber}")`);
    await prisma.accountSettlement.delete({ where: { id: settlement.body.data.id } });
  }

  // ── 8. Petty Cash, Vendor Payment, Purchase Return, Sales Return — reference codes on the primary ledger row ──
  console.log('\n[8] Petty Cash / Vendor Payment / Returns — RET/PCA/VPAY reference codes');
  {
    const users = await api('GET', '/users', token);
    const salesUser = users.body.data.find((x: any) => x.id !== login.body.data.user.id) ?? users.body.data[0];
    const petty = await api('POST', '/cash/petty-cash', token, { toUserId: salesUser.id, amount: 100, note: 'TST-SGC petty cash' });
    assert(petty.status === 201 || petty.status === 200, `petty cash issued (status ${petty.status})`);
    assert(/^PCA-\d{4,}$/.test(petty.body.data.referenceNo ?? ''), `transaction carries a PCA-#### reference (got "${petty.body.data.referenceNo}")`);

    const pay = await api('POST', `/vendors/${vendorId}/pay`, token, { amount: 10, method: 'CASH' });
    assert(pay.status === 201, `vendor payment posted (status ${pay.status})`);
    assert(/^VPAY-\d{4,}$/.test(pay.body.data.referenceNo ?? ''), `payment entry carries a VPAY-#### reference (got "${pay.body.data.referenceNo}")`);

    const med = await prisma.medicineMaster.findFirstOrThrow({ where: { code: 'TST-SGC-MED' } });
    const batches = await api('GET', `/pharmacy/medicines/${med.id}/batches`, token);
    const batch = batches.body.data[0];
    const ret = await api('POST', '/vendors/purchase-returns', token, {
      vendorId, lines: [{ medicineId: med.id, batchId: batch.id, returnUnitQuantity: 1 }], reason: 'TST-SGC purchase return test',
    });
    assert(ret.status === 201, `purchase return posted (status ${ret.status})`);
    assert(/^RET-\d{4,}$/.test(ret.body.data.referenceNo ?? ''), `purchase return entry carries a RET-#### reference (got "${ret.body.data.referenceNo}")`);
  }

  // ── 9. Historical records are untouched ──────────────────────────────────
  console.log('\n[9] Historical records — pre-existing codes never renamed');
  {
    const oldest = await prisma.purchase.findFirst({ orderBy: { createdAt: 'asc' } });
    if (oldest) {
      assert(!!oldest.purchaseNumber, `oldest existing Purchase still has its original purchaseNumber ("${oldest.purchaseNumber}")`);
    } else {
      console.log('  (no pre-existing purchases in this DB to check — skipped)');
    }
  }

  console.log(`\n━━━ Results: ${passed} passed, ${failed} failed ━━━`);
  await cleanupMedicines(prisma, TEST_MED_CODES);
  await cleanupVendors(prisma);
  await prisma.$disconnect();
  if (failed > 0) process.exit(1);
}

main().catch((err) => {
  console.error('Test run crashed:', err);
  process.exit(1);
});
