import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Department, DepartmentFilterState } from '../types/department';
import { User } from '../types';
import {
  getHospitalProfile,
  formatHospitalAddress,
  getProfileFieldValue,
} from './hospitalProfileService';
import { formatDisplayDate } from '../utils/dateConstants';

/**
 * Generates dynamic YYYY-MM-DD date string based on current local date
 */
export function getDynamicDateString(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Formats operational capabilities into a clean comma-separated string
 */
export function formatDepartmentCapabilities(d: Department): string {
  const caps: string[] = [];
  if (d.opdEnabled) caps.push('OPD');
  if (d.observationEnabled) caps.push('Observation');
  if (d.emergencyEnabled) caps.push('Emergency');
  if (d.admissionEnabled) caps.push('Admission');
  if (d.pharmacyRelated) caps.push('Pharmacy');
  return caps.length > 0 ? caps.join(', ') : 'None';
}

/**
 * Generate and download a real PDF file for filtered departments
 */
export async function downloadDepartmentPDF(
  departments: Department[],
  filters: DepartmentFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  // Initialize Landscape A4 (297mm x 210mm)
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  const regNumber = getProfileFieldValue(profile.registrationNumber);
  const taxNumber = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  // 1. Hospital Header
  // Logo placeholder crest
  doc.setFillColor(8, 119, 90); // #08775A
  doc.roundedRect(14, 12, 11, 11, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.text('CHSS', 19.5, 18.5, { align: 'center' });

  // Hospital Name & Governance
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(hospitalName, 28, 17);

  doc.setTextColor(71, 85, 105); // slate-600
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'Executive Hospital Management System • Central Administrative Governance',
    28,
    21.5
  );

  // Registration & Tax info (strictly non-fabricated)
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFontSize(7);
  doc.text(
    `Reg No: ${regNumber}   •   Tax / NTN: ${taxNumber}   •   Phone: ${phone}`,
    28,
    25.5
  );

  // Document Title badge on right
  doc.setFillColor(239, 250, 245); // #effaf5
  doc.setDrawColor(194, 231, 219); // #c2e7db
  doc.roundedRect(217, 12, 66, 13, 1.5, 1.5, 'FD');

  doc.setTextColor(8, 119, 90); // #08775A
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('DEPARTMENT DIRECTORY', 250, 17.5, { align: 'center' });

  doc.setTextColor(71, 85, 105);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Records: ${departments.length}`, 250, 22.5, { align: 'center' });

  // 2. Metadata Box
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(14, 29, 269, 15, 1.5, 1.5, 'FD');

  doc.setFontSize(7);
  // Column 1: Generated By
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'bold');
  doc.text('GENERATED BY:', 18, 34);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'normal');
  doc.text(`${generatedByName} (${generatedByRole})`, 41, 34);

  // Column 1b: Generated On
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'bold');
  doc.text('GENERATED ON:', 18, 39.5);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'normal');
  doc.text(generatedOn, 41, 39.5);

  // Column 2: Active Filters
  const filterSummary = [
    `Type: ${filters.type}`,
    `Status: ${filters.status}`,
    `Access: ${filters.capability}`,
  ].join('  |  ');
  const searchSummary = filters.searchTerm.trim()
    ? `Search: "${filters.searchTerm.trim()}"`
    : 'Search: None';

  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'bold');
  doc.text('APPLIED FILTERS:', 130, 34);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'normal');
  doc.text(filterSummary, 155, 34);

  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'bold');
  doc.text('SEARCH QUERY:', 130, 39.5);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'normal');
  doc.text(searchSummary, 155, 39.5);

  // 3. Departments Table
  const tableHead = [
    [
      'Department Code',
      'Department Name',
      'Type',
      'Head / In-charge',
      'Location / Extension',
      'Operational Access',
      'Doctors',
      'Staff',
      'Status',
    ],
  ];

  const tableRows = departments.map((d) => [
    d.code,
    d.name,
    d.type,
    d.headName || 'Not Assigned',
    `${d.location || 'N/A'}${d.contactExtension ? ` (Ext. ${d.contactExtension})` : ''}`,
    formatDepartmentCapabilities(d),
    String(d.doctorCount ?? 0),
    String(d.staffCount ?? 0),
    d.status,
  ]);

  autoTable(doc, {
    head: tableHead,
    body: tableRows,
    startY: 47,
    margin: { left: 14, right: 14, top: 14, bottom: 18 },
    showHead: 'everyPage',
    headStyles: {
      fillColor: [8, 119, 90], // #08775A
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
      halign: 'left',
      cellPadding: 2,
    },
    bodyStyles: {
      fontSize: 7.2,
      textColor: [30, 41, 59],
      cellPadding: 2,
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
    },
    alternateRowStyles: {
      fillColor: [248, 252, 250],
    },
    columnStyles: {
      0: { cellWidth: 26, fontStyle: 'bold', textColor: [8, 119, 90] },
      1: { cellWidth: 42, fontStyle: 'bold' },
      2: { cellWidth: 26 },
      3: { cellWidth: 38 },
      4: { cellWidth: 42 },
      5: { cellWidth: 45 },
      6: { cellWidth: 16, halign: 'center' },
      7: { cellWidth: 16, halign: 'center' },
      8: { cellWidth: 18, halign: 'center', fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      // Highlight Status column
      if (data.section === 'body' && data.column.index === 8) {
        if (data.cell.raw === 'Active') {
          data.cell.styles.textColor = [5, 122, 85]; // green
        } else {
          data.cell.styles.textColor = [100, 116, 139]; // slate
        }
      }
    },
  });

  // 4. Footers with dynamic page numbers on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(120, 135, 125);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Official Institutional Record • ${hospitalName} • Confidential`,
      14,
      203
    );
    doc.text(`Page ${i} of ${totalPages}`, 283, 203, { align: 'right' });
  }

  // Save the real .pdf file directly in browser
  const filename = `CHSS_Department_Directory_${dateStr}.pdf`;
  doc.save(filename);
}

/**
 * Generate and download a real Excel (.xlsx) workbook for filtered departments
 */
export async function downloadDepartmentExcel(
  departments: Department[],
  filters: DepartmentFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  // 1. Sheet 1: Department Directory
  const departmentRows = departments.map((d) => ({
    'Department Code': d.code,
    'Department Name': d.name,
    'Department Type': d.type,
    'Description': d.description || 'N/A',
    'Head / In-charge': d.headName || 'Not Assigned',
    'Location': d.location || 'N/A',
    'Contact / Extension': d.contactExtension || 'N/A',
    'OPD Enabled': d.opdEnabled ? 'Yes' : 'No',
    'Observation Enabled': d.observationEnabled ? 'Yes' : 'No',
    'Emergency Enabled': d.emergencyEnabled ? 'Yes' : 'No',
    'Admission Enabled': d.admissionEnabled ? 'Yes' : 'No',
    'Pharmacy Related': d.pharmacyRelated ? 'Yes' : 'No',
    'Doctors Count': d.doctorCount ?? 0,
    'Staff Count': d.staffCount ?? 0,
    'Services Count': d.serviceCount ?? 0,
    'Wards Count': d.wardCount ?? 0,
    'Status': d.status,
    'Created By': d.createdBy || 'System',
    'Created Date': d.createdAt || 'N/A',
    'Updated By': d.updatedBy || 'System',
    'Updated Date': d.updatedAt || 'N/A',
  }));

  // 2. Sheet 2: Export Information (Metadata)
  const metaRows = [
    { Property: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Property: 'Report Name', Value: 'Department Directory' },
    { Property: 'Generated By', Value: generatedByName },
    { Property: 'Role', Value: generatedByRole },
    { Property: 'Generated On', Value: generatedOn },
    { Property: 'Applied Search', Value: filters.searchTerm.trim() || 'None' },
    { Property: 'Department Type Filter', Value: filters.type },
    { Property: 'Status Filter', Value: filters.status },
    { Property: 'Capability Filter', Value: filters.capability },
    { Property: 'Total Exported Records', Value: departments.length },
    { Property: 'Registration Number', Value: getProfileFieldValue(profile.registrationNumber) },
    { Property: 'Tax / NTN Number', Value: getProfileFieldValue(profile.taxNumber) },
    { Property: 'Hospital Phone', Value: getProfileFieldValue(profile.primaryPhone) },
    { Property: 'Hospital Email', Value: getProfileFieldValue(profile.primaryEmail) },
    { Property: 'Hospital Address', Value: formatHospitalAddress(profile) },
  ];

  // Create workbook
  const wb = XLSX.utils.book_new();

  // Add Department Directory Sheet
  const wsDepts = XLSX.utils.json_to_sheet(departmentRows);
  wsDepts['!cols'] = [
    { wch: 18 }, // Code
    { wch: 26 }, // Name
    { wch: 18 }, // Type
    { wch: 34 }, // Description
    { wch: 24 }, // Head
    { wch: 22 }, // Location
    { wch: 20 }, // Contact / Extension
    { wch: 14 }, // OPD
    { wch: 18 }, // Observation
    { wch: 18 }, // Emergency
    { wch: 18 }, // Admission
    { wch: 18 }, // Pharmacy
    { wch: 14 }, // Doctors
    { wch: 12 }, // Staff
    { wch: 14 }, // Services
    { wch: 12 }, // Wards
    { wch: 12 }, // Status
    { wch: 24 }, // Created By
    { wch: 22 }, // Created Date
    { wch: 24 }, // Updated By
    { wch: 22 }, // Updated Date
  ];
  XLSX.utils.book_append_sheet(wb, wsDepts, 'Department Directory');

  // Add Export Information Sheet
  const wsMeta = XLSX.utils.json_to_sheet(metaRows);
  wsMeta['!cols'] = [{ wch: 26 }, { wch: 50 }];
  XLSX.utils.book_append_sheet(wb, wsMeta, 'Export Information');

  // Write and download actual .xlsx file directly
  const filename = `CHSS_Department_Directory_${dateStr}.xlsx`;
  XLSX.writeFile(wb, filename);
}
