import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Patient, PatientFilterState, ImportPatientRowResult } from '../types/patient';
import { User } from '../types';
import { getHospitalProfile, getProfileFieldValue } from './hospitalProfileService';
import { formatDisplayDate } from '../utils/dateConstants';

export function formatPatientFilterSummary(filters: PatientFilterState): string {
  const parts: string[] = [];
  if (filters.searchTerm.trim()) parts.push(`Search: "${filters.searchTerm.trim()}"`);
  if (filters.gender !== 'ALL') parts.push(`Gender: ${filters.gender}`);
  if (filters.payerType !== 'ALL') parts.push(`Payer: ${filters.payerType}`);
  if (filters.panelId !== 'ALL') parts.push(`Panel ID: ${filters.panelId}`);
  if (filters.status !== 'ALL') parts.push(`Status: ${filters.status}`);
  return parts.length > 0 ? parts.join(' | ') : 'All Active, Inactive & Deceased Patient Records';
}

/**
 * Generate and download real .pdf for Patient Registry Directory
 */
export async function downloadPatientsPDF(
  patients: Patient[],
  filters: PatientFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Authorized Hospital User';
  const generatedByRole = currentUser?.role || 'Management';

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  // Header decorative green bar
  doc.setFillColor(8, 119, 90); // #08775A
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Hospital Name & Subtitle
  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text(hospitalName, margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(
    'Executive Hospital Information System • Master Patient Index & Permanent Identity Directory',
    margin,
    19
  );

  // Profile Badges
  const regNo = getProfileFieldValue(profile.registrationNumber);
  const taxNo = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Reg No: ${regNo}   |   NTN/Tax: ${taxNo}   |   Phone: ${phone}`, margin, 24);

  // Right Title Box
  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 80, 8, 80, 18, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(8, 119, 90);
  doc.text('PATIENT REGISTRY', pageWidth - margin - 75, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(`Total Filtered Records: ${patients.length}`, pageWidth - margin - 75, 21);

  // Meta Section
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, 28, pageWidth - margin, 28);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Generated By: ${generatedByName} (${generatedByRole})`, margin, 32);
  doc.text(`Generated On: ${generatedOn}`, margin + 110, 32);

  const filterSummary = formatPatientFilterSummary(filters);
  doc.text(`Active Filters: ${filterSummary}`, margin, 36);

  // Table Data (privacy rule: Do NOT include CNIC in default PDF directory unless requested)
  const tableData = patients.map((p, idx) => [
    String(idx + 1),
    p.mrNumber,
    p.fullName,
    p.primaryPhone || '—',
    `${p.age}y / ${p.gender === 'Other / Not Specified' ? 'Other' : p.gender}`,
    p.payerType === 'Corporate / Panel' ? 'Panel' : 'Self Pay',
    p.payerType === 'Corporate / Panel' ? (p.panelName || 'Corporate Panel') : 'Direct Patient',
    p.registrationDate || '—',
    p.status,
  ]);

  autoTable(doc, {
    startY: 40,
    margin: { left: margin, right: margin, bottom: 16 },
    head: [
      [
        '#',
        'MR Number',
        'Patient Full Name',
        'Contact Phone',
        'Age / Gender',
        'Payer Type',
        'Panel / Payer Entity',
        'Reg Date',
        'Status',
      ],
    ],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [8, 119, 90], // Emerald
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'left',
    },
    styles: {
      fontSize: 7.5,
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
      cellPadding: 2,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 26, fontStyle: 'bold' },
      2: { cellWidth: 46 },
      3: { cellWidth: 28 },
      4: { cellWidth: 24 },
      5: { cellWidth: 22 },
      6: { cellWidth: 60 },
      7: { cellWidth: 24 },
      8: { cellWidth: 22, halign: 'center' },
    },
    didDrawCell: (data) => {
      // Color-code status in table
      if (data.section === 'body' && data.column.index === 8) {
        const val = String(data.cell.raw);
        if (val === 'ACTIVE') {
          doc.setTextColor(8, 119, 90);
        } else if (val === 'INACTIVE') {
          doc.setTextColor(100, 116, 139);
        } else if (val === 'DECEASED') {
          doc.setTextColor(51, 65, 85);
        }
      }
    },
  });

  // Footer on each page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Confidential & Privileged • CH Sharif and Saeed Hospital • Master Patient Registry Directory`,
      margin,
      pageHeight - 7
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 7);
  }

  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`patient_registry_${dateStr}.pdf`);
}

/**
 * Generate and download real .xlsx for Patient Registry
 */
export async function downloadPatientsExcel(
  patients: Patient[],
  filters: PatientFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Authorized Hospital User';
  const generatedByRole = currentUser?.role || 'Management';

  // Sheet 1: Patient Registry
  const rows = patients.map((p, idx) => ({
    'Sr #': idx + 1,
    'MR Number': p.mrNumber,
    'Full Name': p.fullName,
    'Father / Guardian': p.fatherGuardianName || '—',
    'Guardian Relation': p.guardianRelation || '—',
    'Date of Birth': p.dateOfBirth || '—',
    Age: p.age,
    'Age Estimated': p.ageIsEstimated ? 'Yes' : 'No',
    Gender: p.gender,
    CNIC: p.cnic || '—',
    Passport: p.passportNumber || '—',
    'Primary Phone': p.primaryPhone,
    'Alternate Phone': p.alternatePhone || '—',
    Email: p.email || '—',
    Address: [p.addressLine1, p.addressLine2, p.city, p.province, p.country]
      .filter(Boolean)
      .join(', '),
    'Blood Group': p.bloodGroup || 'Unknown',
    'Payer Type': p.payerType,
    'Corporate Panel': p.payerType === 'Corporate / Panel' ? p.panelName : '—',
    'Panel Member ID': p.payerType === 'Corporate / Panel' ? p.panelMemberId : '—',
    'Emergency Contact': p.emergencyContactName
      ? `${p.emergencyContactName} (${p.emergencyContactRelation || 'Relation'}) - ${p.emergencyContactPhone || ''}`
      : '—',
    Status: p.status,
    'Registration Date': p.registrationDate,
    'Last Visit Date': p.lastVisitDate || 'Never visited',
    'Created By': p.createdBy,
    'Updated By': p.updatedBy,
  }));

  const ws = XLSX.utils.json_to_sheet(rows);

  // Column widths
  ws['!cols'] = [
    { wch: 6 }, // Sr #
    { wch: 18 }, // MR Number
    { wch: 28 }, // Full Name
    { wch: 24 }, // Father/Guardian
    { wch: 16 }, // Guardian Relation
    { wch: 14 }, // DOB
    { wch: 8 }, // Age
    { wch: 14 }, // Age Estimated
    { wch: 12 }, // Gender
    { wch: 18 }, // CNIC
    { wch: 14 }, // Passport
    { wch: 16 }, // Phone
    { wch: 16 }, // Alt Phone
    { wch: 26 }, // Email
    { wch: 38 }, // Address
    { wch: 12 }, // Blood Group
    { wch: 18 }, // Payer Type
    { wch: 36 }, // Panel Name
    { wch: 20 }, // Panel Member ID
    { wch: 32 }, // Emergency Contact
    { wch: 12 }, // Status
    { wch: 16 }, // Registration Date
    { wch: 16 }, // Last Visit Date
    { wch: 22 }, // Created By
    { wch: 22 }, // Updated By
  ];

  // Sheet 2: Export Information
  const metaRows = [
    { Property: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Property: 'Registration Number', Value: getProfileFieldValue(profile.registrationNumber) },
    { Property: 'National Tax Number (NTN)', Value: getProfileFieldValue(profile.taxNumber) },
    { Property: 'Primary Contact', Value: getProfileFieldValue(profile.primaryPhone) },
    { Property: 'Document Title', Value: 'Master Patient Registry Directory' },
    { Property: 'Exported Records', Value: patients.length },
    { Property: 'Generated By', Value: `${generatedByName} (${generatedByRole})` },
    { Property: 'Generated On', Value: generatedOn },
    { Property: 'Applied Filters', Value: formatPatientFilterSummary(filters) },
    {
      Property: 'Governance Note',
      Value:
        'MR numbers are permanent unique hospital identifiers. Master patient records must be retained in compliance with healthcare data regulations.',
    },
  ];

  const metaWs = XLSX.utils.json_to_sheet(metaRows);
  metaWs['!cols'] = [{ wch: 28 }, { wch: 70 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Patient Registry');
  XLSX.utils.book_append_sheet(wb, metaWs, 'Export Information');

  const dateStr = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `patient_registry_${dateStr}.xlsx`);
}

/**
 * Generate standardized .xlsx import template for Patients
 */
export function downloadPatientImportTemplate(): void {
  // Columns requested in Specification:
  // full_name, father_guardian_name, guardian_relation, date_of_birth, age, gender,
  // cnic, passport_number, primary_phone, alternate_phone, email, address_line_1,
  // address_line_2, city, province, country, blood_group, payer_type, panel_code,
  // panel_member_id, emergency_contact_name, emergency_contact_relation, emergency_contact_phone, status
  const sampleRows = [
    {
      full_name: 'Muhammad Farhan',
      father_guardian_name: 'Muhammad Akram',
      guardian_relation: 'Father',
      date_of_birth: '1988-03-15',
      age: '', // will be computed from DOB if left empty
      gender: 'Male',
      cnic: '35201-1234567-1',
      passport_number: '',
      primary_phone: '0300-1234567',
      alternate_phone: '0321-7654321',
      email: 'farhan.akram@example.com',
      address_line_1: 'House 14, Street 2, Sector B, DHA',
      address_line_2: 'Phase 5',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      blood_group: 'B+',
      payer_type: 'Self Pay',
      panel_code: '',
      panel_member_id: '',
      emergency_contact_name: 'Muhammad Akram',
      emergency_contact_relation: 'Father',
      emergency_contact_phone: '0300-7654321',
      status: 'ACTIVE',
    },
    {
      full_name: 'Samina Perveen',
      father_guardian_name: 'Tariq Mehmood',
      guardian_relation: 'Spouse',
      date_of_birth: '',
      age: 45, // manual age when DOB is unknown
      gender: 'Female',
      cnic: '35202-7654321-2',
      passport_number: '',
      primary_phone: '0333-9876543',
      alternate_phone: '',
      email: '',
      address_line_1: 'Flat 5, Block G, Johar Town',
      address_line_2: '',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      blood_group: 'O+',
      payer_type: 'Corporate / Panel',
      panel_code: 'PNL-SLI',
      panel_member_id: 'SLI-112233-PK',
      emergency_contact_name: 'Tariq Mehmood',
      emergency_contact_relation: 'Spouse',
      emergency_contact_phone: '0333-1122334',
      status: 'ACTIVE',
    },
  ];

  const ws = XLSX.utils.json_to_sheet(sampleRows);
  ws['!cols'] = [
    { wch: 22 }, // full_name
    { wch: 22 }, // father_guardian_name
    { wch: 16 }, // guardian_relation
    { wch: 14 }, // date_of_birth
    { wch: 8 },  // age
    { wch: 12 }, // gender
    { wch: 18 }, // cnic
    { wch: 16 }, // passport_number
    { wch: 16 }, // primary_phone
    { wch: 16 }, // alternate_phone
    { wch: 26 }, // email
    { wch: 30 }, // address_line_1
    { wch: 20 }, // address_line_2
    { wch: 14 }, // city
    { wch: 14 }, // province
    { wch: 14 }, // country
    { wch: 12 }, // blood_group
    { wch: 18 }, // payer_type
    { wch: 14 }, // panel_code
    { wch: 18 }, // panel_member_id
    { wch: 22 }, // emergency_contact_name
    { wch: 22 }, // emergency_contact_relation
    { wch: 22 }, // emergency_contact_phone
    { wch: 12 }, // status
  ];

  const guideRows = [
    {
      Field: 'full_name',
      Required: 'YES',
      Description: 'Full patient legal name.',
      Example: 'Muhammad Farhan',
    },
    {
      Field: 'father_guardian_name',
      Required: 'Optional',
      Description: 'Name of father, spouse, or guardian.',
      Example: 'Muhammad Akram',
    },
    {
      Field: 'guardian_relation',
      Required: 'Optional',
      Description: 'Father | Mother | Spouse | Sibling | Son | Daughter | Relative | Guardian | Other',
      Example: 'Father',
    },
    {
      Field: 'date_of_birth',
      Required: 'Conditional',
      Description: 'Format: YYYY-MM-DD. If provided, age will be calculated automatically.',
      Example: '1988-03-15',
    },
    {
      Field: 'age',
      Required: 'Conditional',
      Description: 'If date_of_birth is empty, provide numeric age (0-125). ageIsEstimated will be set true.',
      Example: '45',
    },
    {
      Field: 'gender',
      Required: 'YES',
      Description: 'Male | Female | Other / Not Specified',
      Example: 'Male',
    },
    {
      Field: 'cnic',
      Required: 'Optional',
      Description: '13-digit Pakistani CNIC format: XXXXX-XXXXXXX-X. Exact duplicates are rejected.',
      Example: '35201-1234567-1',
    },
    {
      Field: 'primary_phone',
      Required: 'YES',
      Description: 'Active mobile/contact number (at least 10 digits).',
      Example: '0300-1234567',
    },
    {
      Field: 'blood_group',
      Required: 'Optional',
      Description: 'Unknown | A+ | A- | B+ | B- | AB+ | AB- | O+ | O-',
      Example: 'B+',
    },
    {
      Field: 'payer_type',
      Required: 'YES',
      Description: 'Self Pay | Corporate / Panel',
      Example: 'Corporate / Panel',
    },
    {
      Field: 'panel_code',
      Required: 'Conditional',
      Description: 'Required if payer_type is Corporate / Panel. Codes: PNL-SLI (State Life), PNL-EFU (EFU Life), PNL-JUB (Jubilee), PNL-FFO (Fauji Foundation), PNL-OGD (OGDCL), PNL-PSO (PSO)',
      Example: 'PNL-SLI',
    },
    {
      Field: 'panel_member_id',
      Required: 'Conditional',
      Description: 'Corporate/Insurance Card No or Employee/Member ID.',
      Example: 'SLI-112233-PK',
    },
    {
      Field: 'status',
      Required: 'Optional',
      Description: 'ACTIVE | INACTIVE | DECEASED (Default: ACTIVE)',
      Example: 'ACTIVE',
    },
    {
      Field: 'MR Number Rule',
      Required: 'DO NOT INCLUDE',
      Description: 'Permanent MR Numbers are auto-generated sequentially by the system to prevent collisions.',
      Example: 'Auto-assigned by system',
    },
  ];

  const guideWs = XLSX.utils.json_to_sheet(guideRows);
  guideWs['!cols'] = [{ wch: 22 }, { wch: 14 }, { wch: 60 }, { wch: 25 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Import Template');
  XLSX.utils.book_append_sheet(wb, guideWs, 'Instructions & Reference');

  XLSX.writeFile(wb, 'patient_import_template.xlsx');
}

/**
 * Download error rows from import operation
 */
export function downloadImportErrorRows(errorRows: ImportPatientRowResult[]): void {
  const rows = errorRows.map((r) => ({
    'Row #': r.rowNumber,
    Status: r.status,
    'Existing MR': r.existingMrNumber || '—',
    'Error Details': r.errors.join('; '),
    ...r.data,
  }));

  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Import Errors');

  const dateStr = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `patient_import_errors_${dateStr}.xlsx`);
}
