import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { HospitalService, ServiceFilterState } from '../types/serviceRates';
import { User } from '../types';
import {
  getHospitalProfile,
  getProfileFieldValue,
} from './hospitalProfileService';
import { formatDisplayDate } from '../utils/dateConstants';
import { DepartmentService } from './departmentService';

/**
 * Dynamic YYYY-MM-DD string
 */
export function getDynamicDateString(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Format currency amount
 */
export function formatCurrencyRate(amount?: number | null, currency = 'PKR'): string {
  return `${currency} ${(amount ?? 0).toLocaleString('en-PK')}`;
}

/**
 * Download real .pdf document for Services & Rates
 */
export async function downloadServicesPDF(
  services: HospitalService[],
  filters: ServiceFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  // Header band
  doc.setFillColor(8, 119, 90); // #08775A
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Hospital Name & Subtitle
  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text(hospitalName, margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(
    'Executive Hospital Information System • Central Charge Master & Service Catalog',
    margin,
    19
  );

  // Profile Badges
  const regNo = getProfileFieldValue(profile.registrationNumber);
  const taxNo = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(
    `Reg No: ${regNo}   |   NTN/Tax: ${taxNo}   |   Phone: ${phone}`,
    margin,
    24
  );

  // Right Title Box
  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 75, 8, 75, 18, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(8, 119, 90);
  doc.text('SERVICES & RATES DIRECTORY', pageWidth - margin - 70, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(`Total Records in Scope: ${services.length}`, pageWidth - margin - 70, 21);

  // Metadata Panel
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, 28, pageWidth - margin * 2, 13, 2, 2, 'FD');

  const deptFilterLabel =
    filters.departmentId === 'All'
      ? 'All Departments'
      : DepartmentService.getDepartmentById(filters.departmentId)?.name || filters.departmentId;

  const appliedFilters = [
    `Search: ${filters.searchTerm.trim() ? `"${filters.searchTerm.trim()}"` : 'None'}`,
    `Dept: ${deptFilterLabel}`,
    `Category: ${filters.category}`,
    `Panel: ${filters.panelEligible}`,
    `Status: ${filters.status}`,
  ].join('  •  ');

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('GENERATED BY:', margin + 3, 33);
  doc.text('GENERATED ON:', margin + 65, 33);
  doc.text('ACTIVE FILTERS:', margin + 130, 33);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`${generatedByName} (${generatedByRole})`, margin + 3, 38);
  doc.text(generatedOn, margin + 65, 38);
  doc.setFont('helvetica', 'normal');
  doc.text(appliedFilters, margin + 130, 38);

  // Table Data (Strict 8 landscape columns)
  const headers = [
    [
      'Code',
      'Service Name',
      'Department',
      'Category',
      'Billing Unit',
      'Standard Rate',
      'Panel',
      'Status',
    ],
  ];

  const body = services.map((s) => [
    s.code,
    s.name,
    s.departmentName,
    s.category,
    s.billingUnit,
    formatCurrencyRate(s.standardRate, s.currency),
    s.panelEligible ? 'Yes' : 'No',
    s.status,
  ]);

  autoTable(doc, {
    head: headers,
    body: body,
    startY: 44,
    margin: { left: margin, right: margin, bottom: 16 },
    theme: 'grid',
    styles: {
      fontSize: 8,
      cellPadding: 2,
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
      textColor: [30, 41, 59],
      valign: 'middle',
    },
    headStyles: {
      fillColor: [239, 250, 245],
      textColor: [8, 119, 90],
      fontStyle: 'bold',
      lineColor: [194, 231, 219],
      lineWidth: 0.2,
    },
    alternateRowStyles: {
      fillColor: [253, 254, 253],
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 28 }, // Code
      1: { cellWidth: 68 }, // Name
      2: { cellWidth: 50 }, // Department
      3: { cellWidth: 32 }, // Category
      4: { cellWidth: 30 }, // Billing Unit
      5: { halign: 'right', fontStyle: 'bold', cellWidth: 30 }, // Rate
      6: { halign: 'center', cellWidth: 16 }, // Panel
      7: { halign: 'center', cellWidth: 16 }, // Status
    },
    showHead: 'everyPage',
    didDrawPage: (data) => {
      const pageNumber = (doc.internal as any).getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Services & Rates Master Directory • ${hospitalName} Central Health Governance`,
        margin,
        pageHeight - 6
      );
      doc.text(
        `Page ${data.pageNumber} of ${pageNumber}`,
        pageWidth - margin - 20,
        pageHeight - 6
      );
    },
  });

  const filename = `CHSS_Services_Directory_${dateStr}.pdf`;
  doc.save(filename);
}

/**
 * Download real .xlsx workbook for Services & Rates
 */
export async function downloadServicesExcel(
  services: HospitalService[],
  filters: ServiceFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const departments = DepartmentService.getDepartments();
  const deptMap = new Map(departments.map((d) => [d.id, d.code]));

  // Sheet 1: Services Catalog
  const serviceRows = services.map((s) => ({
    'Service Code': s.code,
    'Service Name': s.name,
    'Department Code': deptMap.get(s.departmentId) || '',
    'Department Name': s.departmentName,
    'Category': s.category,
    'Description': s.description || '',
    'Billing Unit': s.billingUnit,
    'Standard Rate': s.standardRate,
    'Currency': s.currency,
    'Panel Eligible': s.panelEligible ? 'Yes' : 'No',
    'Discount Allowed': s.discountAllowed ? 'Yes' : 'No',
    'Manual Rate Override Allowed': s.manualRateOverrideAllowed ? 'Yes' : 'No',
    'Linked Invoices': s.linkedInvoiceCount ?? 0,
    'Linked Panel Rules': s.linkedPanelRuleCount ?? 0,
    'Status': s.status,
    'Created By': s.createdBy,
    'Created At': s.createdAt,
    'Updated By': s.updatedBy,
    'Updated At': s.updatedAt,
  }));

  const worksheet1 = XLSX.utils.json_to_sheet(serviceRows);

  worksheet1['!cols'] = [
    { wch: 16 }, // Service Code
    { wch: 38 }, // Service Name
    { wch: 16 }, // Dept Code
    { wch: 28 }, // Dept Name
    { wch: 18 }, // Category
    { wch: 45 }, // Description
    { wch: 18 }, // Billing Unit
    { wch: 14 }, // Standard Rate
    { wch: 10 }, // Currency
    { wch: 14 }, // Panel Eligible
    { wch: 16 }, // Discount Allowed
    { wch: 24 }, // Manual Rate Override
    { wch: 14 }, // Linked Invoices
    { wch: 18 }, // Linked Panel Rules
    { wch: 12 }, // Status
    { wch: 32 }, // Created By
    { wch: 22 }, // Created At
    { wch: 32 }, // Updated By
    { wch: 22 }, // Updated At
  ];

  // Sheet 2: Export Information
  const deptFilterLabel =
    filters.departmentId === 'All'
      ? 'All Departments'
      : DepartmentService.getDepartmentById(filters.departmentId)?.name || filters.departmentId;

  const exportMetadata = [
    { Field: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Field: 'Report Title', Value: 'Services & Rates Master Catalog' },
    { Field: 'Generated By', Value: `${generatedByName} (${generatedByRole})` },
    { Field: 'Generated On', Value: generatedOn },
    { Field: 'Total Services Exported', Value: services.length },
    { Field: 'Search Query', Value: filters.searchTerm.trim() || 'None' },
    { Field: 'Department Filter', Value: deptFilterLabel },
    { Field: 'Category Filter', Value: filters.category },
    { Field: 'Panel Eligibility Filter', Value: filters.panelEligible },
    { Field: 'Status Filter', Value: filters.status },
    { Field: 'Hospital Registration No', Value: getProfileFieldValue(profile.registrationNumber) },
    { Field: 'Hospital NTN / Tax No', Value: getProfileFieldValue(profile.taxNumber) },
    { Field: 'Hospital Phone', Value: getProfileFieldValue(profile.primaryPhone) },
  ];

  const worksheet2 = XLSX.utils.json_to_sheet(exportMetadata);
  worksheet2['!cols'] = [{ wch: 28 }, { wch: 50 }];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet1, 'Services & Rates');
  XLSX.utils.book_append_sheet(workbook, worksheet2, 'Export Information');

  const filename = `CHSS_Services_Directory_${dateStr}.xlsx`;
  XLSX.writeFile(workbook, filename);
}

/**
 * Generate and download Excel Import Template
 */
export function downloadServicesImportTemplate(): void {
  const templateRows = [
    {
      service_code: 'SRV-OPD-099',
      service_name: 'Dermatology Initial Consultation',
      department_code: 'DEP-DERM',
      category: 'Consultation',
      description: 'Skin, hair and nail specialist evaluation',
      billing_unit: 'Per Consultation',
      standard_rate: 3000,
      panel_eligible: 'Yes',
      discount_allowed: 'Yes',
      manual_rate_override_allowed: 'No',
      status: 'Active',
    },
    {
      service_code: 'SRV-LAB-HBA1C',
      service_name: 'HbA1c Glycated Hemoglobin Test',
      department_code: 'DEP-PATH',
      category: 'Laboratory',
      description: '3-month average plasma glucose concentration',
      billing_unit: 'Per Test',
      standard_rate: 1400,
      panel_eligible: 'Yes',
      discount_allowed: 'Yes',
      manual_rate_override_allowed: 'No',
      status: 'Active',
    },
  ];

  const worksheet = XLSX.utils.json_to_sheet(templateRows);
  worksheet['!cols'] = [
    { wch: 16 },
    { wch: 32 },
    { wch: 18 },
    { wch: 16 },
    { wch: 40 },
    { wch: 18 },
    { wch: 14 },
    { wch: 14 },
    { wch: 16 },
    { wch: 26 },
    { wch: 12 },
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Services_Template');

  XLSX.writeFile(workbook, 'Hospital_Services_Import_Template.xlsx');
}
