import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { StaffUser, StaffUserFilterState } from '../types/staffUser';
import { User } from '../types';
import {
  getHospitalProfile,
  getProfileFieldValue,
} from './hospitalProfileService';
import { formatDisplayDate } from '../utils/dateConstants';

export function getDynamicDateString(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function formatFilterSummary(filters: StaffUserFilterState): string {
  const parts: string[] = [];
  if (filters.searchTerm) parts.push(`Search: "${filters.searchTerm}"`);
  if (filters.departmentId && filters.departmentId !== 'ALL') parts.push(`Dept: ${filters.departmentId}`);
  if (filters.staffCategory && filters.staffCategory !== 'ALL') parts.push(`Category: ${filters.staffCategory}`);
  if (filters.accessType && filters.accessType !== 'ALL') parts.push(`Access: ${filters.accessType === 'PORTAL_USER' ? 'Portal User' : 'Staff Record Only'}`);
  if (filters.assignedPortal && filters.assignedPortal !== 'ALL') parts.push(`Portal: ${filters.assignedPortal}`);
  if (filters.status && filters.status !== 'ALL') parts.push(`Status: ${filters.status}`);
  return parts.length > 0 ? parts.join(' | ') : 'All Active & Inactive Staff Records';
}

/**
 * Download real .pdf document for Staff Users Directory
 */
export async function downloadStaffUsersPDF(
  users: StaffUser[],
  filters: StaffUserFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Unauthenticated Session';
  const generatedByRole = currentUser?.role || 'No Active Role';

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  // Header band
  doc.setFillColor(8, 119, 90); // #08775A
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Hospital Name & Subtitle
  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text(hospitalName, margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(
    'Executive Hospital Information System • Staff Directory & Workstation Entitlements',
    margin,
    19
  );

  // Profile Badges
  const regNo = getProfileFieldValue(profile.registrationNumber);
  const taxNo = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(
    `Reg No: ${regNo}   |   NTN/Tax: ${taxNo}   |   Phone: ${phone}`,
    margin,
    24
  );

  // Right Title Box
  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 80, 8, 80, 18, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(8, 119, 90);
  doc.text('HOSPITAL STAFF DIRECTORY', pageWidth - margin - 75, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Official Directory Roll • ${users.length} Staff`, pageWidth - margin - 75, 21);

  // Divider line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(margin, 28, pageWidth - margin, 28);

  // Metadata Panel
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, 31, pageWidth - margin * 2, 14, 1.5, 1.5, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text('Generated By:', margin + 4, 37);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`${generatedByName} (${generatedByRole})`, margin + 26, 37);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Generated On:', margin + 110, 37);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(generatedOn, margin + 132, 37);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Applied Filters:', margin + 4, 42);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const filterSummary = formatFilterSummary(filters);
  doc.text(filterSummary, margin + 26, 42);

  // Table Columns
  const tableHeaders = [
    'Employee Code',
    'Staff Name',
    'Designation',
    'Department',
    'Access / Portal',
    'Role',
    'Status',
  ];

  const tableBody = users.map((u) => [
    u.employeeCode,
    u.fullName,
    u.designation,
    u.departmentName,
    u.accessType === 'PORTAL_USER' ? (u.assignedPortal ? u.assignedPortal.toUpperCase() : 'PORTAL USER') : 'Staff Record Only',
    u.staffRole || '—',
    u.status,
  ]);

  autoTable(doc, {
    head: [tableHeaders],
    body: tableBody,
    startY: 48,
    margin: { left: margin, right: margin, bottom: 18 },
    theme: 'grid',
    headStyles: {
      fillColor: [8, 119, 90],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
      cellPadding: 2.5,
    },
    styles: {
      fontSize: 8,
      cellPadding: 2.2,
      textColor: [15, 23, 42],
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 26 },
      1: { cellWidth: 48 },
      2: { cellWidth: 48 },
      3: { cellWidth: 52 },
      4: { cellWidth: 32 },
      5: { cellWidth: 40 },
      6: { cellWidth: 22, halign: 'center' },
    },
    didDrawPage: (data) => {
      // Footer on every page
      const pageNum = data.pageNumber;
      const totalPages = (doc.internal as any).getNumberOfPages();

      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.3);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184); // slate-400
      doc.text(
        'CONFIDENTIAL • Sharif & Saeed Executive Hospital Management System • Internal Operational Directory',
        margin,
        pageHeight - 7
      );

      const pageStr = `Page ${pageNum} of ${totalPages}`;
      doc.text(pageStr, pageWidth - margin - 20, pageHeight - 7);
    },
  });

  const fileDate = getDynamicDateString(now);
  doc.save(`hospital_staff_directory_${fileDate}.pdf`);
}

/**
 * Download real .xlsx workbook with 2 sheets
 */
export async function downloadStaffUsersExcel(
  users: StaffUser[],
  filters: StaffUserFilterState,
  currentUser: User | null
): Promise<void> {
  const profile = getHospitalProfile();
  const now = new Date();
  const timeStr = now.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;

  // Sheet 1: Staff Directory
  const directoryRows = users.map((u) => ({
    'Staff ID': u.id,
    'Employee Code': u.employeeCode,
    'Full Name': u.fullName,
    'Father / Guardian Name': u.fatherGuardianName || '—',
    Phone: u.phone,
    'Alternate Phone': u.alternatePhone || '—',
    Email: u.email,
    CNIC: u.cnic || '—',
    Designation: u.designation,
    Department: u.departmentName,
    'Staff Category': u.staffCategory,
    'Access Type': u.accessType === 'PORTAL_USER' ? 'Portal User' : 'Staff Record Only',
    'Assigned Portal': u.assignedPortal ? u.assignedPortal.toUpperCase() : '—',
    'Staff Role': u.staffRole || '—',
    Username: u.username || '—',
    Status: u.status,
    'Last Login': u.lastLoginAt || 'Never',
    'Created By': u.createdBy,
    'Created Date': u.createdAt,
    'Updated By': u.updatedBy,
    'Updated Date': u.updatedAt,
  }));

  // Sheet 2: Export Information
  const exportInfoRows = [
    { Property: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Property: 'Registration Number', Value: getProfileFieldValue(profile.registrationNumber) },
    { Property: 'NTN / Tax Number', Value: getProfileFieldValue(profile.taxNumber) },
    { Property: 'Export Category', Value: 'Hospital Staff Directory & Workstation Entitlements' },
    { Property: 'Total Records Exported', Value: users.length },
    { Property: 'Generated By', Value: `${currentUser?.name || 'Authorized Management'} (${currentUser?.role || 'Management'})` },
    { Property: 'Generated On', Value: generatedOn },
    { Property: 'Applied Filters', Value: formatFilterSummary(filters) },
    { Property: 'Confidentiality Warning', Value: 'STRICTLY CONFIDENTIAL. Internal operational directory for hospital administration use only.' },
  ];

  const wb = XLSX.utils.book_new();
  const wsDirectory = XLSX.utils.json_to_sheet(directoryRows);
  const wsInfo = XLSX.utils.json_to_sheet(exportInfoRows);

  XLSX.utils.book_append_sheet(wb, wsDirectory, 'Staff Directory');
  XLSX.utils.book_append_sheet(wb, wsInfo, 'Export Information');

  const fileDate = getDynamicDateString(now);
  XLSX.writeFile(wb, `hospital_staff_directory_${fileDate}.xlsx`);
}
