import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getHospitalProfile, getProfileFieldValue, formatHospitalAddress } from './hospitalProfileService';
import { formatDisplayDate } from '../utils/dateConstants';
import { User } from '../types';

/**
 * Generic, REAL PDF/Excel/Print export for any tabular report — same
 * `jspdf` + `xlsx` + browser-print pattern already proven in
 * `adminUserExportService.ts`, generalized over columns/rows so Finance
 * Control's Balance Sheets and Account Settlements (and Front Desk's own
 * Balance Sheet) don't each re-implement it. Every export shows the actual
 * `currentUser` as "Generated By" and the real applied filters — never a
 * hardcoded name or fabricated row (Balance Sheet & Account Settlement
 * Guide §12 rule 9).
 */

export interface ExportColumn<T> {
  header: string;
  align?: 'left' | 'right' | 'center';
  width?: number;
  /** PDF/Print cell text. */
  cell: (row: T) => string;
  /** Excel cell value (defaults to `cell` if omitted) — pass a raw number here to keep it numeric in the spreadsheet. */
  excelValue?: (row: T) => string | number;
}

export interface ExportRequest<T> {
  documentTitle: string;
  documentSubtitle?: string;
  filenamePrefix: string;
  columns: ExportColumn<T>[];
  rows: T[];
  currentUser: User | null;
  periodLabel?: string;
  filters?: string[];
}

function nowStamp() {
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit', hour12: true });
  return { now, dateStr, generatedOn: `${formatDisplayDate(now)}, ${timeStr}` };
}

export function downloadTablePDF<T>({ documentTitle, documentSubtitle, filenamePrefix, columns, rows, currentUser, periodLabel, filters }: ExportRequest<T>): void {
  const profile = getHospitalProfile();
  const { dateStr, generatedOn } = nowStamp();
  const generatedByName = currentUser?.name || 'Unauthenticated Session';
  const generatedByRole = currentUser?.role || 'No Active Role';

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  doc.setFillColor(8, 119, 90);
  doc.rect(0, 0, pageWidth, 4, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(profile.name || 'CH Sharif and Saeed Hospital', margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(documentSubtitle || 'Hospital Finance Control', margin, 19);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(
    `Reg No: ${getProfileFieldValue(profile.registrationNumber)}   |   NTN/Tax: ${getProfileFieldValue(profile.taxNumber)}   |   Phone: ${getProfileFieldValue(profile.primaryPhone)}`,
    margin,
    24,
  );

  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 80, 8, 80, 18, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(8, 119, 90);
  doc.text(documentTitle.toUpperCase(), pageWidth - margin - 75, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`${rows.length} record${rows.length === 1 ? '' : 's'}${periodLabel ? ` • ${periodLabel}` : ''}`, pageWidth - margin - 75, 21);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(margin, 28, pageWidth - margin, 28);

  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Generated On:', margin, 34);
  doc.setFont('helvetica', 'normal');
  doc.text(generatedOn, margin + 24, 34);

  doc.setFont('helvetica', 'bold');
  doc.text('Authorized By:', margin + 80, 34);
  doc.setFont('helvetica', 'normal');
  doc.text(`${generatedByName} (${generatedByRole})`, margin + 104, 34);

  if (filters && filters.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.text('Filters:', margin + 180, 34);
    doc.setFont('helvetica', 'normal');
    doc.text(filters.join(' | '), margin + 194, 34);
  }

  autoTable(doc, {
    startY: 38,
    margin: { left: margin, right: margin, bottom: 16 },
    head: [columns.map((c) => c.header)],
    body: rows.map((row) => columns.map((c) => c.cell(row))),
    theme: 'grid',
    headStyles: { fillColor: [8, 119, 90], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold', halign: 'left', cellPadding: 2.2 },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: Object.fromEntries(columns.map((c, i) => [i, { halign: c.align || 'left', ...(c.width ? { cellWidth: c.width } : {}) }])),
    didDrawPage: (data) => {
      const pageCount = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.4);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(148, 163, 184);
      doc.text('CONFIDENTIAL • HOSPITAL FINANCE RECORD', margin, pageHeight - 7);
      doc.text(`Page ${data.pageNumber} of ${pageCount}`, pageWidth - margin - 22, pageHeight - 7);
    },
  });

  doc.save(`${filenamePrefix}_${dateStr}.pdf`);
}

export function downloadTableExcel<T>({ documentTitle, filenamePrefix, columns, rows, currentUser, periodLabel, filters }: ExportRequest<T>): void {
  const profile = getHospitalProfile();
  const { generatedOn } = nowStamp();

  const dataRows = rows.map((row) => Object.fromEntries(columns.map((c) => [c.header, c.excelValue ? c.excelValue(row) : c.cell(row)])));
  const wsData = XLSX.utils.json_to_sheet(dataRows);
  wsData['!cols'] = columns.map(() => ({ wch: 20 }));

  const infoRows = [
    { Property: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Property: 'Hospital Address', Value: formatHospitalAddress(profile) },
    { Property: 'Report Document', Value: documentTitle },
    { Property: 'Period', Value: periodLabel || 'N/A' },
    { Property: 'Export Date & Time', Value: generatedOn },
    { Property: 'Exported By', Value: currentUser ? `${currentUser.name} (${currentUser.role})` : 'Unauthenticated Session' },
    { Property: 'Total Records Exported', Value: rows.length },
    ...(filters && filters.length > 0 ? [{ Property: 'Applied Filters', Value: filters.join(' | ') }] : []),
  ];
  const wsInfo = XLSX.utils.json_to_sheet(infoRows);
  wsInfo['!cols'] = [{ wch: 26 }, { wch: 55 }];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, wsData, documentTitle.slice(0, 31));
  XLSX.utils.book_append_sheet(workbook, wsInfo, 'Export Information');

  const { dateStr } = nowStamp();
  XLSX.writeFile(workbook, `${filenamePrefix}_${dateStr}.xlsx`);
}

export function downloadTableCSV<T>({ filenamePrefix, columns, rows }: ExportRequest<T>): void {
  const dataRows = rows.map((row) => Object.fromEntries(columns.map((c) => [c.header, c.excelValue ? c.excelValue(row) : c.cell(row)])));
  const wsData = XLSX.utils.json_to_sheet(dataRows);
  const csv = XLSX.utils.sheet_to_csv(wsData);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const { dateStr } = nowStamp();
  a.download = `${filenamePrefix}_${dateStr}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function printTable<T>({ documentTitle, documentSubtitle, columns, rows, currentUser, periodLabel, filters }: ExportRequest<T>): void {
  const profile = getHospitalProfile();
  const { generatedOn } = nowStamp();
  const userName = currentUser?.name || 'Unauthenticated Session';
  const userRole = currentUser?.role || 'No Active Role';

  const printWindow = window.open('', '_blank', 'width=1100,height=800');
  if (!printWindow) return;

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${documentTitle} — ${profile.name || 'CH Sharif and Saeed Hospital'}</title>
        <style>
          @page { size: landscape; margin: 12mm; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #0f172a; margin: 0; padding: 16px; font-size: 11px; }
          .header { border-bottom: 2px solid #08775A; padding-bottom: 12px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: flex-start; }
          .hospital-title { font-size: 18px; font-weight: bold; color: #0f172a; margin: 0 0 4px 0; }
          .hospital-subtitle { font-size: 11px; color: #64748b; margin: 0 0 6px 0; }
          .reg-info { font-size: 10px; color: #475569; }
          .badge { background: #effaf5; border: 1px solid #c2e7db; color: #08775A; padding: 4px 10px; border-radius: 6px; font-weight: bold; font-size: 11px; text-align: right; }
          .meta-strip { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px; margin-bottom: 14px; font-size: 10.5px; display: flex; justify-content: space-between; flex-wrap: wrap; gap: 6px; }
          table { width: 100%; border-collapse: collapse; font-size: 10.5px; }
          th { background: #08775A; color: white; text-align: left; padding: 8px 10px; font-size: 10px; text-transform: uppercase; font-weight: 600; border: 1px solid #08775A; }
          td { padding: 7px 10px; border: 1px solid #e2e8f0; }
          tr:nth-child(even) td { background: #f8fafc; }
          .footer { margin-top: 20px; border-top: 1px solid #e2e8f0; padding-top: 8px; font-size: 9px; color: #94a3b8; display: flex; justify-content: space-between; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="hospital-title">${profile.name || 'CH Sharif and Saeed Hospital'}</div>
            <div class="hospital-subtitle">${documentSubtitle || 'Hospital Finance Control'}</div>
            <div class="reg-info">
              Reg: ${getProfileFieldValue(profile.registrationNumber)} | NTN: ${getProfileFieldValue(profile.taxNumber)} | Phone: ${getProfileFieldValue(profile.primaryPhone)}
            </div>
          </div>
          <div class="badge">
            ${documentTitle.toUpperCase()}<br/>
            <span style="font-weight: normal; font-size: 9px; color: #64748b;">${rows.length} record${rows.length === 1 ? '' : 's'}</span>
          </div>
        </div>

        <div class="meta-strip">
          <div><strong>Printed:</strong> ${generatedOn}</div>
          <div><strong>Authorized Officer:</strong> ${userName} (${userRole})</div>
          ${periodLabel ? `<div><strong>Period:</strong> ${periodLabel}</div>` : ''}
          ${filters && filters.length > 0 ? `<div><strong>Filters:</strong> ${filters.join(' | ')}</div>` : ''}
        </div>

        <table>
          <thead>
            <tr>${columns.map((c) => `<th style="text-align:${c.align || 'left'}">${c.header}</th>`).join('')}</tr>
          </thead>
          <tbody>
            ${rows
              .map(
                (row) => `
              <tr>${columns.map((c) => `<td style="text-align:${c.align || 'left'}">${c.cell(row)}</td>`).join('')}</tr>
            `,
              )
              .join('')}
          </tbody>
        </table>

        <div class="footer">
          <div>CONFIDENTIAL • OFFICIAL HOSPITAL FINANCE RECORD • UNAUTHORIZED REPRODUCTION FORBIDDEN</div>
          <div>Report generated from Executive HMS Portal</div>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 250);
}
