import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import {
  Ward,
  Room,
  Bed,
  WardFilterState,
  RoomFilterState,
  BedFilterState,
} from '../types/wardsRoomsBeds';
import { User } from '../types';
import {
  getHospitalProfile,
  getProfileFieldValue,
} from './hospitalProfileService';
import { formatDisplayDate } from '../utils/dateConstants';
import { DepartmentService } from './departmentService';

export function getDynamicDateString(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function formatPKR(val?: number | null): string {
  return `PKR ${(val ?? 0).toLocaleString('en-PK')}`;
}

// ----------------------------------------------------
// WARDS EXPORT
// ----------------------------------------------------
export async function downloadWardsPDF(
  wards: Ward[],
  filtersOrUser?: Partial<WardFilterState> | User | null,
  userParam?: User | null
): Promise<void> {
  const isUser = filtersOrUser && ('role' in filtersOrUser || 'username' in filtersOrUser);
  const currentUser = isUser ? (filtersOrUser as User) : userParam;
  const rawFilters = isUser ? null : (filtersOrUser as Partial<WardFilterState> | null);
  const filters: WardFilterState = {
    searchTerm: rawFilters?.searchTerm || '',
    departmentId: rawFilters?.departmentId || 'All',
    wardType: rawFilters?.wardType || 'All',
    status: rawFilters?.status || 'All',
  };

  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  doc.setFillColor(8, 119, 90);
  doc.rect(0, 0, pageWidth, 4, 'F');

  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(hospitalName, margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Executive Inpatient Accommodation Master • Ward Infrastructure Setup', margin, 19);

  const regNo = getProfileFieldValue(profile.registrationNumber);
  const taxNo = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Reg No: ${regNo}   |   NTN/Tax: ${taxNo}   |   Phone: ${phone}`, margin, 24);

  // Right Title Box
  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 75, 8, 75, 18, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(8, 119, 90);
  doc.text('WARD DIRECTORY', pageWidth - margin - 70, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(`Total Records: ${wards.length}`, pageWidth - margin - 70, 21);

  // Filter Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, 28, pageWidth - margin * 2, 13, 2, 2, 'FD');

  const deptLabel =
    filters.departmentId === 'All'
      ? 'All Departments'
      : DepartmentService.getDepartmentById(filters.departmentId)?.name || filters.departmentId;

  const appliedFilters = [
    `Search: ${filters.searchTerm.trim() ? `"${filters.searchTerm.trim()}"` : 'None'}`,
    `Dept: ${deptLabel}`,
    `Type: ${filters.wardType}`,
    `Status: ${filters.status}`,
  ].join('  •  ');

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('GENERATED BY:', margin + 3, 33);
  doc.text('GENERATED ON:', margin + 65, 33);
  doc.text('ACTIVE FILTERS:', margin + 130, 33);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`${generatedByName} (${generatedByRole})`, margin + 3, 38);
  doc.text(generatedOn, margin + 65, 38);
  doc.setFont('helvetica', 'normal');
  doc.text(appliedFilters, margin + 130, 38);

  const headers = [
    ['Ward Code', 'Ward Name', 'Department', 'Type', 'Floor / Location', 'Rooms', 'Total Beds', 'Available', 'Status'],
  ];

  const body = wards.map((w) => [
    w.code,
    w.name,
    w.departmentName,
    w.wardType,
    w.location ? `${w.floor || ''} - ${w.location}` : w.floor || 'N/A',
    String(w.roomCount),
    String(w.bedCount),
    String(w.availableBeds ?? 0),
    w.status,
  ]);

  autoTable(doc, {
    head: headers,
    body: body,
    startY: 44,
    margin: { left: margin, right: margin, bottom: 16 },
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2, lineColor: [226, 232, 240], lineWidth: 0.1, textColor: [30, 41, 59] },
    headStyles: { fillColor: [239, 250, 245], textColor: [8, 119, 90], fontStyle: 'bold', lineColor: [194, 231, 219] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 26 },
      1: { cellWidth: 50 },
      2: { cellWidth: 50 },
      3: { cellWidth: 28 },
      4: { cellWidth: 48 },
      5: { halign: 'center', cellWidth: 16 },
      6: { halign: 'center', cellWidth: 18 },
      7: { halign: 'center', fontStyle: 'bold', cellWidth: 18 },
      8: { halign: 'center', cellWidth: 15 },
    },
    showHead: 'everyPage',
    didDrawPage: (data) => {
      const pageNum = (doc.internal as any).getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Ward Directory • ${hospitalName} Central Health Governance`, margin, pageHeight - 6);
      doc.text(`Page ${data.pageNumber} of ${pageNum}`, pageWidth - margin - 20, pageHeight - 6);
    },
  });

  doc.save(`CHSS_Ward_Directory_${dateStr}.pdf`);
}

export async function downloadWardsExcel(
  wards: Ward[],
  filtersOrUser?: Partial<WardFilterState> | User | null,
  userParam?: User | null
): Promise<void> {
  const isUser = filtersOrUser && ('role' in filtersOrUser || 'username' in filtersOrUser);
  const currentUser = isUser ? (filtersOrUser as User) : userParam;
  const rawFilters = isUser ? null : (filtersOrUser as Partial<WardFilterState> | null);
  const filters: WardFilterState = {
    searchTerm: rawFilters?.searchTerm || '',
    departmentId: rawFilters?.departmentId || 'All',
    wardType: rawFilters?.wardType || 'All',
    status: rawFilters?.status || 'All',
  };

  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const rows = wards.map((w) => ({
    'Ward Code': w.code,
    'Ward Name': w.name,
    'Department Name': w.departmentName,
    'Ward Type': w.wardType,
    'Gender Policy': w.genderPolicy || 'N/A',
    'Floor': w.floor || '',
    'Location': w.location || '',
    'Description': w.description || '',
    'Rooms Configured': w.roomCount,
    'Total Beds': w.bedCount,
    'Available Beds': w.availableBeds ?? 0,
    'Status': w.status,
    'Created By': w.createdBy,
    'Created At': w.createdAt,
    'Updated By': w.updatedBy,
    'Updated At': w.updatedAt,
  }));

  const worksheet1 = XLSX.utils.json_to_sheet(rows);
  worksheet1['!cols'] = [
    { wch: 16 }, { wch: 32 }, { wch: 28 }, { wch: 16 }, { wch: 16 },
    { wch: 14 }, { wch: 30 }, { wch: 40 }, { wch: 16 }, { wch: 14 },
    { wch: 14 }, { wch: 12 }, { wch: 30 }, { wch: 22 }, { wch: 30 }, { wch: 22 },
  ];

  const exportMetadata = [
    { Field: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Field: 'Report Title', Value: 'Ward Directory & Master Accommodation' },
    { Field: 'Generated By', Value: `${generatedByName} (${generatedByRole})` },
    { Field: 'Generated On', Value: generatedOn },
    { Field: 'Total Wards Exported', Value: wards.length },
    { Field: 'Search Query', Value: filters.searchTerm.trim() || 'None' },
    { Field: 'Department Filter', Value: filters.departmentId },
    { Field: 'Ward Type Filter', Value: filters.wardType },
    { Field: 'Status Filter', Value: filters.status },
    { Field: 'Hospital Registration No', Value: getProfileFieldValue(profile.registrationNumber) },
    { Field: 'Hospital NTN / Tax No', Value: getProfileFieldValue(profile.taxNumber) },
    { Field: 'Hospital Phone', Value: getProfileFieldValue(profile.primaryPhone) },
  ];

  const worksheet2 = XLSX.utils.json_to_sheet(exportMetadata);
  worksheet2['!cols'] = [{ wch: 28 }, { wch: 50 }];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet1, 'Ward Directory');
  XLSX.utils.book_append_sheet(workbook, worksheet2, 'Export Information');

  XLSX.writeFile(workbook, `CHSS_Ward_Directory_${dateStr}.xlsx`);
}

export function downloadWardsImportTemplate(): void {
  const rows = [
    {
      ward_code: 'WRD-SURG-01',
      ward_name: 'Post-Operative Surgical Ward',
      department_code: 'DEP-SURG',
      ward_type: 'General',
      gender_policy: 'Mixed',
      floor: '3rd Floor',
      location: 'South Wing Surgical Tower',
      description: 'Immediate post-surgical recovery and intermediate nursing observation',
      status: 'Active',
    },
  ];

  const worksheet = XLSX.utils.json_to_sheet(rows);
  worksheet['!cols'] = [
    { wch: 16 }, { wch: 32 }, { wch: 18 }, { wch: 16 }, { wch: 16 },
    { wch: 14 }, { wch: 30 }, { wch: 45 }, { wch: 12 },
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Wards_Template');
  XLSX.writeFile(workbook, 'Hospital_Wards_Import_Template.xlsx');
}

// ----------------------------------------------------
// ROOMS EXPORT
// ----------------------------------------------------
export async function downloadRoomsPDF(
  rooms: Room[],
  filtersOrUser?: Partial<RoomFilterState> | User | null,
  userParam?: User | null
): Promise<void> {
  const isUser = filtersOrUser && ('role' in filtersOrUser || 'username' in filtersOrUser);
  const currentUser = isUser ? (filtersOrUser as User) : userParam;
  const rawFilters = isUser ? null : (filtersOrUser as Partial<RoomFilterState> | null);
  const filters: RoomFilterState = {
    searchTerm: rawFilters?.searchTerm || '',
    wardId: rawFilters?.wardId || 'All',
    roomType: rawFilters?.roomType || 'All',
    status: rawFilters?.status || 'All',
  };

  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  doc.setFillColor(8, 119, 90);
  doc.rect(0, 0, pageWidth, 4, 'F');

  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(hospitalName, margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Executive Inpatient Accommodation Master • Room Inventory & Capacity', margin, 19);

  const regNo = getProfileFieldValue(profile.registrationNumber);
  const taxNo = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Reg No: ${regNo}   |   NTN/Tax: ${taxNo}   |   Phone: ${phone}`, margin, 24);

  // Right Title Box
  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 75, 8, 75, 18, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(8, 119, 90);
  doc.text('ROOM DIRECTORY', pageWidth - margin - 70, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(`Total Records: ${rooms.length}`, pageWidth - margin - 70, 21);

  // Filter Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, 28, pageWidth - margin * 2, 13, 2, 2, 'FD');

  const appliedFilters = [
    `Search: ${filters.searchTerm.trim() ? `"${filters.searchTerm.trim()}"` : 'None'}`,
    `Ward: ${filters.wardId === 'All' ? 'All Wards' : filters.wardId}`,
    `Type: ${filters.roomType}`,
    `Status: ${filters.status}`,
  ].join('  •  ');

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('GENERATED BY:', margin + 3, 33);
  doc.text('GENERATED ON:', margin + 65, 33);
  doc.text('ACTIVE FILTERS:', margin + 130, 33);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`${generatedByName} (${generatedByRole})`, margin + 3, 38);
  doc.text(generatedOn, margin + 65, 38);
  doc.setFont('helvetica', 'normal');
  doc.text(appliedFilters, margin + 130, 38);

  const headers = [
    ['Room Code', 'Number', 'Room Name', 'Ward', 'Department', 'Type', 'Capacity', 'Beds Config', 'Daily Rate', 'Status'],
  ];

  const body = rooms.map((r) => [
    r.code,
    r.roomNumber,
    r.name,
    r.wardName,
    r.departmentName,
    r.roomType,
    String(r.capacity),
    String(r.bedsConfigured),
    formatPKR(r.dailyRoomRate),
    r.status,
  ]);

  autoTable(doc, {
    head: headers,
    body: body,
    startY: 44,
    margin: { left: margin, right: margin, bottom: 16 },
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2, lineColor: [226, 232, 240], lineWidth: 0.1, textColor: [30, 41, 59] },
    headStyles: { fillColor: [239, 250, 245], textColor: [8, 119, 90], fontStyle: 'bold', lineColor: [194, 231, 219] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 26 },
      1: { cellWidth: 18 },
      2: { cellWidth: 38 },
      3: { cellWidth: 42 },
      4: { cellWidth: 44 },
      5: { cellWidth: 24 },
      6: { halign: 'center', cellWidth: 16 },
      7: { halign: 'center', fontStyle: 'bold', cellWidth: 18 },
      8: { halign: 'right', fontStyle: 'bold', cellWidth: 28 },
      9: { halign: 'center', cellWidth: 15 },
    },
    showHead: 'everyPage',
    didDrawPage: (data) => {
      const pageNum = (doc.internal as any).getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Room Directory • ${hospitalName} Central Health Governance`, margin, pageHeight - 6);
      doc.text(`Page ${data.pageNumber} of ${pageNum}`, pageWidth - margin - 20, pageHeight - 6);
    },
  });

  doc.save(`CHSS_Room_Directory_${dateStr}.pdf`);
}

export async function downloadRoomsExcel(
  rooms: Room[],
  filtersOrUser?: Partial<RoomFilterState> | User | null,
  userParam?: User | null
): Promise<void> {
  const isUser = filtersOrUser && ('role' in filtersOrUser || 'username' in filtersOrUser);
  const currentUser = isUser ? (filtersOrUser as User) : userParam;
  const rawFilters = isUser ? null : (filtersOrUser as Partial<RoomFilterState> | null);
  const filters: RoomFilterState = {
    searchTerm: rawFilters?.searchTerm || '',
    wardId: rawFilters?.wardId || 'All',
    roomType: rawFilters?.roomType || 'All',
    status: rawFilters?.status || 'All',
  };

  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const rows = rooms.map((r) => ({
    'Room Code': r.code,
    'Room Number': r.roomNumber,
    'Room Name': r.name,
    'Ward Name': r.wardName,
    'Department Name': r.departmentName,
    'Room Type': r.roomType,
    'Floor': r.floor || '',
    'Capacity': r.capacity,
    'Beds Configured': r.bedsConfigured,
    'Daily Room Rate (PKR)': r.dailyRoomRate,
    'Status': r.status,
    'Created By': r.createdBy,
    'Created At': r.createdAt,
    'Updated By': r.updatedBy,
    'Updated At': r.updatedAt,
  }));

  const worksheet1 = XLSX.utils.json_to_sheet(rows);
  worksheet1['!cols'] = [
    { wch: 16 }, { wch: 14 }, { wch: 28 }, { wch: 28 }, { wch: 28 },
    { wch: 16 }, { wch: 14 }, { wch: 12 }, { wch: 16 }, { wch: 22 },
    { wch: 12 }, { wch: 30 }, { wch: 22 }, { wch: 30 }, { wch: 22 },
  ];

  const exportMetadata = [
    { Field: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Field: 'Report Title', Value: 'Room Directory & Master Inventory' },
    { Field: 'Generated By', Value: `${generatedByName} (${generatedByRole})` },
    { Field: 'Generated On', Value: generatedOn },
    { Field: 'Total Rooms Exported', Value: rooms.length },
    { Field: 'Search Query', Value: filters.searchTerm.trim() || 'None' },
    { Field: 'Ward Filter', Value: filters.wardId },
    { Field: 'Room Type Filter', Value: filters.roomType },
    { Field: 'Status Filter', Value: filters.status },
    { Field: 'Hospital Registration No', Value: getProfileFieldValue(profile.registrationNumber) },
    { Field: 'Hospital NTN / Tax No', Value: getProfileFieldValue(profile.taxNumber) },
    { Field: 'Hospital Phone', Value: getProfileFieldValue(profile.primaryPhone) },
  ];

  const worksheet2 = XLSX.utils.json_to_sheet(exportMetadata);
  worksheet2['!cols'] = [{ wch: 28 }, { wch: 50 }];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet1, 'Room Directory');
  XLSX.utils.book_append_sheet(workbook, worksheet2, 'Export Information');

  XLSX.writeFile(workbook, `CHSS_Room_Directory_${dateStr}.xlsx`);
}

export function downloadRoomsImportTemplate(): void {
  const rows = [
    {
      room_code: 'RM-SURG-301',
      room_number: '301',
      room_name: 'Post-Op Observation Suite',
      ward_code: 'WRD-SURG-01',
      room_type: 'Semi-Private',
      floor: '3rd Floor',
      capacity: 2,
      daily_room_rate: 6000,
      status: 'Active',
    },
  ];

  const worksheet = XLSX.utils.json_to_sheet(rows);
  worksheet['!cols'] = [
    { wch: 16 }, { wch: 14 }, { wch: 28 }, { wch: 18 }, { wch: 16 },
    { wch: 14 }, { wch: 12 }, { wch: 16 }, { wch: 12 },
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Rooms_Template');
  XLSX.writeFile(workbook, 'Hospital_Rooms_Import_Template.xlsx');
}

// ----------------------------------------------------
// BEDS EXPORT
// ----------------------------------------------------
export async function downloadBedsPDF(
  beds: Bed[],
  filtersOrUser?: Partial<BedFilterState> | User | null,
  userParam?: User | null
): Promise<void> {
  const isUser = filtersOrUser && ('role' in filtersOrUser || 'username' in filtersOrUser);
  const currentUser = isUser ? (filtersOrUser as User) : userParam;
  const rawFilters = isUser ? null : (filtersOrUser as Partial<BedFilterState> | null);
  const filters: BedFilterState = {
    searchTerm: rawFilters?.searchTerm || '',
    wardId: rawFilters?.wardId || 'All',
    roomId: rawFilters?.roomId || 'All',
    bedType: rawFilters?.bedType || 'All',
    occupancyStatus: rawFilters?.occupancyStatus || 'All',
    operationalStatus: rawFilters?.operationalStatus || 'All',
  };

  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  doc.setFillColor(8, 119, 90);
  doc.rect(0, 0, pageWidth, 4, 'F');

  const hospitalName = profile.name || 'CH Sharif and Saeed Hospital';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(hospitalName, margin, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Executive Inpatient Accommodation Master • Bed Directory & Status', margin, 19);

  const regNo = getProfileFieldValue(profile.registrationNumber);
  const taxNo = getProfileFieldValue(profile.taxNumber);
  const phone = getProfileFieldValue(profile.primaryPhone);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Reg No: ${regNo}   |   NTN/Tax: ${taxNo}   |   Phone: ${phone}`, margin, 24);

  // Right Title Box
  doc.setFillColor(239, 250, 245);
  doc.setDrawColor(194, 231, 219);
  doc.roundedRect(pageWidth - margin - 75, 8, 75, 18, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(8, 119, 90);
  doc.text('BED DIRECTORY', pageWidth - margin - 70, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(`Total Records: ${beds.length}`, pageWidth - margin - 70, 21);

  // Filter Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, 28, pageWidth - margin * 2, 13, 2, 2, 'FD');

  const appliedFilters = [
    `Search: ${filters.searchTerm.trim() ? `"${filters.searchTerm.trim()}"` : 'None'}`,
    `Ward: ${filters.wardId === 'All' ? 'All' : filters.wardId}`,
    `Type: ${filters.bedType}`,
    `Occupancy: ${filters.occupancyStatus}`,
    `Operational: ${filters.operationalStatus}`,
  ].join('  •  ');

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('GENERATED BY:', margin + 3, 33);
  doc.text('GENERATED ON:', margin + 65, 33);
  doc.text('ACTIVE FILTERS:', margin + 130, 33);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`${generatedByName} (${generatedByRole})`, margin + 3, 38);
  doc.text(generatedOn, margin + 65, 38);
  doc.setFont('helvetica', 'normal');
  doc.text(appliedFilters, margin + 130, 38);

  const headers = [
    ['Bed Code', 'Number', 'Room', 'Ward', 'Type', 'Daily Rate', 'Occupancy', 'Operational', 'Current Patient'],
  ];

  const body = beds.map((b) => [
    b.code,
    b.bedNumber,
    b.roomName,
    b.wardName,
    b.bedType,
    formatPKR(b.dailyBedRate ?? b.dailyRate ?? 0),
    b.occupancyStatus,
    b.operationalStatus,
    b.occupancyStatus === 'Occupied' ? b.currentPatientName || 'Occupied' : '—',
  ]);

  autoTable(doc, {
    head: headers,
    body: body,
    startY: 44,
    margin: { left: margin, right: margin, bottom: 16 },
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2, lineColor: [226, 232, 240], lineWidth: 0.1, textColor: [30, 41, 59] },
    headStyles: { fillColor: [239, 250, 245], textColor: [8, 119, 90], fontStyle: 'bold', lineColor: [194, 231, 219] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 26 },
      1: { cellWidth: 20 },
      2: { cellWidth: 36 },
      3: { cellWidth: 40 },
      4: { cellWidth: 24 },
      5: { halign: 'right', fontStyle: 'bold', cellWidth: 26 },
      6: { halign: 'center', cellWidth: 22 },
      7: { halign: 'center', cellWidth: 24 },
      8: { cellWidth: 50 },
    },
    showHead: 'everyPage',
    didDrawPage: (data) => {
      const pageNum = (doc.internal as any).getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Bed Directory • ${hospitalName} Central Health Governance`, margin, pageHeight - 6);
      doc.text(`Page ${data.pageNumber} of ${pageNum}`, pageWidth - margin - 20, pageHeight - 6);
    },
  });

  doc.save(`CHSS_Bed_Directory_${dateStr}.pdf`);
}

export async function downloadBedsExcel(
  beds: Bed[],
  filtersOrUser?: Partial<BedFilterState> | User | null,
  userParam?: User | null
): Promise<void> {
  const isUser = filtersOrUser && ('role' in filtersOrUser || 'username' in filtersOrUser);
  const currentUser = isUser ? (filtersOrUser as User) : userParam;
  const rawFilters = isUser ? null : (filtersOrUser as Partial<BedFilterState> | null);
  const filters: BedFilterState = {
    searchTerm: rawFilters?.searchTerm || '',
    wardId: rawFilters?.wardId || 'All',
    roomId: rawFilters?.roomId || 'All',
    bedType: rawFilters?.bedType || 'All',
    occupancyStatus: rawFilters?.occupancyStatus || 'All',
    operationalStatus: rawFilters?.operationalStatus || 'All',
  };

  const profile = getHospitalProfile();
  const now = new Date();
  const dateStr = getDynamicDateString(now);
  const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });
  const generatedOn = `${formatDisplayDate(now)}, ${timeStr}`;
  const generatedByName = currentUser?.name || 'Prof. Dr. Tariq Saeed';
  const generatedByRole = currentUser?.role || 'Super Admin';

  const rows = beds.map((b) => ({
    'Bed Code': b.code,
    'Bed Number': b.bedNumber,
    'Room Name': b.roomName,
    'Ward Name': b.wardName,
    'Department Name': b.departmentName,
    'Bed Type': b.bedType,
    'Daily Rate (PKR)': b.dailyBedRate ?? b.dailyRate ?? 0,
    'Occupancy Status': b.occupancyStatus,
    'Operational Status': b.operationalStatus,
    'Current Patient': b.occupancyStatus === 'Occupied' ? b.currentPatientName || 'Occupied' : '',
    'Created By': b.createdBy,
    'Created At': b.createdAt,
    'Updated By': b.updatedBy,
    'Updated At': b.updatedAt,
  }));

  const worksheet1 = XLSX.utils.json_to_sheet(rows);
  worksheet1['!cols'] = [
    { wch: 16 }, { wch: 14 }, { wch: 28 }, { wch: 28 }, { wch: 28 },
    { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 18 }, { wch: 36 },
    { wch: 30 }, { wch: 22 }, { wch: 30 }, { wch: 22 },
  ];

  const exportMetadata = [
    { Field: 'Hospital Name', Value: profile.name || 'CH Sharif and Saeed Hospital' },
    { Field: 'Report Title', Value: 'Bed Directory & Operational Status' },
    { Field: 'Generated By', Value: `${generatedByName} (${generatedByRole})` },
    { Field: 'Generated On', Value: generatedOn },
    { Field: 'Total Beds Exported', Value: beds.length },
    { Field: 'Search Query', Value: filters.searchTerm.trim() || 'None' },
    { Field: 'Ward Filter', Value: filters.wardId },
    { Field: 'Room Filter', Value: filters.roomId },
    { Field: 'Bed Type Filter', Value: filters.bedType },
    { Field: 'Occupancy Status Filter', Value: filters.occupancyStatus },
    { Field: 'Operational Status Filter', Value: filters.operationalStatus },
    { Field: 'Hospital Registration No', Value: getProfileFieldValue(profile.registrationNumber) },
    { Field: 'Hospital NTN / Tax No', Value: getProfileFieldValue(profile.taxNumber) },
    { Field: 'Hospital Phone', Value: getProfileFieldValue(profile.primaryPhone) },
  ];

  const worksheet2 = XLSX.utils.json_to_sheet(exportMetadata);
  worksheet2['!cols'] = [{ wch: 28 }, { wch: 50 }];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet1, 'Bed Directory');
  XLSX.utils.book_append_sheet(workbook, worksheet2, 'Export Information');

  XLSX.writeFile(workbook, `CHSS_Bed_Directory_${dateStr}.xlsx`);
}

export function downloadBedsImportTemplate(): void {
  const rows = [
    {
      bed_code: 'BED-SURG-301-A',
      bed_number: '301-A',
      room_code: 'RM-SURG-301',
      bed_type: 'Standard',
      daily_rate: 3000,
      operational_status: 'Active',
    },
  ];

  const worksheet = XLSX.utils.json_to_sheet(rows);
  worksheet['!cols'] = [
    { wch: 18 }, { wch: 14 }, { wch: 18 }, { wch: 16 }, { wch: 14 }, { wch: 18 },
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Beds_Template');
  XLSX.writeFile(workbook, 'Hospital_Beds_Import_Template.xlsx');
}
