import { Department, DepartmentHeadOption } from '../../../types/department';

export const MOCK_DEPARTMENT_HEAD_OPTIONS: DepartmentHeadOption[] = [
  {
    userId: 'DOC-001',
    name: 'Prof. Dr. Tariq Saeed',
    designation: 'Professor of Cardiology & Cath Lab Director',
    department: 'Cardiology',
    role: 'Doctor',
  },
  {
    userId: 'DOC-002',
    name: 'Dr. M. Sharif Chaudhary',
    designation: 'Chief Consultant Orthopedic Surgeon',
    department: 'Orthopedics',
    role: 'Doctor',
  },
  {
    userId: 'DOC-003',
    name: 'Dr. Farhana Yasmeen',
    designation: 'Consultant Radiologist & Imaging Head',
    department: 'Radiology',
    role: 'Doctor',
  },
  {
    userId: 'DOC-004',
    name: 'Dr. Ayesha Malik',
    designation: 'Head of Pediatrics & Child Specialist',
    department: 'Pediatrics',
    role: 'Doctor',
  },
  {
    userId: 'DOC-005',
    name: 'Dr. Kamran Javed',
    designation: 'Chief Pathologist & Lab Director',
    department: 'Pathology',
    role: 'Doctor',
  },
  {
    userId: 'DOC-006',
    name: 'Dr. Hamza Rafique',
    designation: 'Emergency Medicine Specialist & In-charge',
    department: 'Emergency',
    role: 'Doctor',
  },
  {
    userId: 'DOC-007',
    name: 'Dr. Shazia Parveen',
    designation: 'Consultant Obstetrician & Gynecologist',
    department: 'Obstetrics & Gynecology',
    role: 'Doctor',
  },
  {
    userId: 'DOC-008',
    name: 'Dr. Bilal Qureshi',
    designation: 'Senior Consultant General Physician',
    department: 'General Medicine',
    role: 'Doctor',
  },
  {
    userId: 'DOC-009',
    name: 'Dr. Noman Arshad',
    designation: 'Consultant General & Laparoscopic Surgeon',
    department: 'General Surgery',
    role: 'Doctor',
  },
  {
    userId: 'DOC-010',
    name: 'Dr. Tahir Mehmood',
    designation: 'Consultant Ophthalmologist & Vitreoretinal Specialist',
    department: 'Ophthalmology',
    role: 'Doctor',
  },
  {
    userId: 'STF-014',
    name: 'Dr. Zeeshan Haider (Pharm-D)',
    designation: 'Chief Pharmacist & Pharmacy In-charge',
    department: 'Pharmacy',
    role: 'Staff',
  },
  {
    userId: 'ADM-002',
    name: 'Mr. Muhammad Usman',
    designation: 'Director Hospital Administration & HR',
    department: 'Administration',
    role: 'Admin',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'DEP-01',
    code: 'DEP-MED',
    name: 'General Medicine',
    type: 'Clinical',
    description: 'Internal medicine, chronic illness management, inpatient diagnostics, and general medical care.',
    headUserId: 'DOC-008',
    headName: 'Dr. Bilal Qureshi',
    contactExtension: 'Ext. 101 / 102',
    location: 'Ground Floor, Block A',
    opdEnabled: true,
    observationEnabled: true,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 8,
    staffCount: 16,
    serviceCount: 14,
    wardCount: 3,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '15 Jan 2024, 09:00 AM',
    updatedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    updatedAt: '05 Sep 2026, 11:20 AM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '15 Jan 2024, 09:00 AM',
  },
  {
    id: 'DEP-02',
    code: 'DEP-SURG',
    name: 'General Surgery',
    type: 'Surgical',
    description: 'Elective and emergency surgical procedures, laparoscopic interventions, and post-operative monitoring.',
    headUserId: 'DOC-009',
    headName: 'Dr. Noman Arshad',
    contactExtension: 'Ext. 201 / 202',
    location: 'First Floor, Surgical Wing B',
    opdEnabled: true,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 7,
    staffCount: 20,
    serviceCount: 22,
    wardCount: 2,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '15 Jan 2024, 09:30 AM',
    updatedBy: 'Dr. Farhana Yasmeen (Admin)',
    updatedAt: '03 Sep 2026, 02:15 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '15 Jan 2024, 09:30 AM',
  },
  {
    id: 'DEP-03',
    code: 'DEP-CARD',
    name: 'Cardiology',
    type: 'Clinical',
    description: 'Cardiovascular diagnostics, coronary angiography, coronary care interventions, and echocardiography.',
    headUserId: 'DOC-001',
    headName: 'Prof. Dr. Tariq Saeed',
    contactExtension: 'Ext. 301 / 302',
    location: 'Second Floor, Heart & Vascular Centre',
    opdEnabled: true,
    observationEnabled: true,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 10,
    staffCount: 28,
    serviceCount: 30,
    wardCount: 2,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '10 Jan 2024, 10:00 AM',
    updatedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    updatedAt: '07 Sep 2026, 04:45 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '10 Jan 2024, 10:00 AM',
  },
  {
    id: 'DEP-04',
    code: 'DEP-PEDS',
    name: 'Pediatrics',
    type: 'Clinical',
    description: 'Comprehensive pediatric care, well-baby clinics, immunization, and specialized pediatric admissions.',
    headUserId: 'DOC-004',
    headName: 'Dr. Ayesha Malik',
    contactExtension: 'Ext. 110 / 112',
    location: 'First Floor, Maternal & Child Centre',
    opdEnabled: true,
    observationEnabled: true,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 6,
    staffCount: 18,
    serviceCount: 16,
    wardCount: 2,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '20 Jan 2024, 11:30 AM',
    updatedBy: 'Dr. Farhana Yasmeen (Admin)',
    updatedAt: '02 Sep 2026, 10:10 AM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '20 Jan 2024, 11:30 AM',
  },
  {
    id: 'DEP-05',
    code: 'DEP-RAD',
    name: 'Radiology',
    type: 'Diagnostic',
    description: 'Multi-slice CT scanning, digital X-Ray, ultrasound Doppler imaging, and diagnostic interventional radiology.',
    headUserId: 'DOC-003',
    headName: 'Dr. Farhana Yasmeen',
    contactExtension: 'Ext. 105 / 106',
    location: 'Ground Floor, Diagnostic Wing A',
    opdEnabled: false,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: false,
    pharmacyRelated: false,
    doctorCount: 5,
    staffCount: 14,
    serviceCount: 28,
    wardCount: 0,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '12 Jan 2024, 02:00 PM',
    updatedBy: 'Dr. Farhana Yasmeen (Admin)',
    updatedAt: '06 Sep 2026, 09:30 AM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '12 Jan 2024, 02:00 PM',
  },
  {
    id: 'DEP-06',
    code: 'DEP-PAT',
    name: 'Pathology',
    type: 'Diagnostic',
    description: 'Automated clinical hematology, biochemistry, microbiology cultures, and certified transfusion blood banking.',
    headUserId: 'DOC-005',
    headName: 'Dr. Kamran Javed',
    contactExtension: 'Ext. 108 / 109',
    location: 'Ground Floor, Laboratory Wing',
    opdEnabled: false,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: false,
    pharmacyRelated: false,
    doctorCount: 4,
    staffCount: 22,
    serviceCount: 45,
    wardCount: 0,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '15 Jan 2024, 03:00 PM',
    updatedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    updatedAt: '01 Sep 2026, 01:20 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '15 Jan 2024, 03:00 PM',
  },
  {
    id: 'DEP-07',
    code: 'DEP-ER',
    name: 'Emergency',
    type: 'Emergency',
    description: '24/7 casualty triage, emergency resuscitation, cardiac arrest response, and acute trauma stabilization.',
    headUserId: 'DOC-006',
    headName: 'Dr. Hamza Rafique',
    contactExtension: 'Ext. 000 / 115',
    location: 'Emergency Wing Entrance, Ground Floor',
    opdEnabled: false,
    observationEnabled: true,
    emergencyEnabled: true,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 12,
    staffCount: 36,
    serviceCount: 18,
    wardCount: 1,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '01 Jan 2024, 08:00 AM',
    updatedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    updatedAt: '07 Sep 2026, 08:15 AM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '01 Jan 2024, 08:00 AM',
  },
  {
    id: 'DEP-08',
    code: 'DEP-PHARM',
    name: 'Pharmacy',
    type: 'Pharmacy',
    description: 'Hospital central retail dispensary, inpatient medication ward stocks, clinical drug verification, and cold-chain handling.',
    headUserId: 'STF-014',
    headName: 'Dr. Zeeshan Haider (Pharm-D)',
    contactExtension: 'Ext. 119 / 120',
    location: 'Central Atrium, Ground Floor',
    opdEnabled: true,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: false,
    pharmacyRelated: true,
    doctorCount: 4,
    staffCount: 18,
    serviceCount: 8,
    wardCount: 0,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '05 Jan 2024, 09:00 AM',
    updatedBy: 'Dr. Farhana Yasmeen (Admin)',
    updatedAt: '04 Sep 2026, 05:10 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '05 Jan 2024, 09:00 AM',
  },
  {
    id: 'DEP-09',
    code: 'DEP-ADMIN',
    name: 'Administration',
    type: 'Administrative',
    description: 'Hospital executive administration, human resources, clinical quality control, and regulatory compliance.',
    headUserId: 'ADM-002',
    headName: 'Mr. Muhammad Usman',
    contactExtension: 'Ext. 500 / 501',
    location: 'Fourth Floor, Executive Directorate',
    opdEnabled: false,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: false,
    pharmacyRelated: false,
    doctorCount: 0,
    staffCount: 24,
    serviceCount: 0,
    wardCount: 0,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '01 Jan 2024, 08:30 AM',
    updatedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    updatedAt: '28 Aug 2026, 11:00 AM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '01 Jan 2024, 08:30 AM',
  },
  {
    id: 'DEP-10',
    code: 'DEP-ORTHO',
    name: 'Orthopedics',
    type: 'Surgical',
    description: 'Trauma surgery, joint replacements, arthroscopic surgery, and musculoskeletal rehabilitation.',
    headUserId: 'DOC-002',
    headName: 'Dr. M. Sharif Chaudhary',
    contactExtension: 'Ext. 215 / 216',
    location: 'Second Floor, Surgical Wing C',
    opdEnabled: true,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 6,
    staffCount: 16,
    serviceCount: 20,
    wardCount: 2,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '15 Jan 2024, 11:00 AM',
    updatedBy: 'Dr. Farhana Yasmeen (Admin)',
    updatedAt: '02 Sep 2026, 03:40 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '15 Jan 2024, 11:00 AM',
  },
  {
    id: 'DEP-11',
    code: 'DEP-GYN',
    name: 'Obstetrics & Gynecology',
    type: 'Surgical',
    description: 'Antenatal care, high-risk obstetrics, normal and caesarean deliveries, and specialized women health.',
    headUserId: 'DOC-007',
    headName: 'Dr. Shazia Parveen',
    contactExtension: 'Ext. 220 / 222',
    location: 'First Floor, Women Health Block',
    opdEnabled: true,
    observationEnabled: true,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 6,
    staffCount: 22,
    serviceCount: 24,
    wardCount: 2,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '18 Jan 2024, 10:30 AM',
    updatedBy: 'Dr. Farhana Yasmeen (Admin)',
    updatedAt: '04 Sep 2026, 01:15 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '18 Jan 2024, 10:30 AM',
  },
  {
    id: 'DEP-12',
    code: 'DEP-EYE',
    name: 'Ophthalmology',
    type: 'Clinical',
    description: 'Comprehensive ophthalmic care, slit-lamp exams, cataract phacoemulsification, and laser vision care.',
    headUserId: 'DOC-010',
    headName: 'Dr. Tahir Mehmood',
    contactExtension: 'Ext. 310 / 311',
    location: 'Third Floor, OPD Suite 3',
    opdEnabled: true,
    observationEnabled: false,
    emergencyEnabled: false,
    admissionEnabled: true,
    pharmacyRelated: false,
    doctorCount: 4,
    staffCount: 10,
    serviceCount: 12,
    wardCount: 1,
    status: 'Active',
    createdBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    createdAt: '01 Feb 2024, 11:00 AM',
    updatedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    updatedAt: '30 Aug 2026, 12:45 PM',
    statusChangedBy: 'Prof. Dr. Tariq Saeed (Super Admin)',
    statusChangedAt: '01 Feb 2024, 11:00 AM',
  },
];

export const SAMPLE_IMPORT_BATCH_DATA: string = `department_code,department_name,department_type,description,head_identifier,contact_extension,location,opd_enabled,observation_enabled,emergency_enabled,admission_enabled,pharmacy_related,status
DEP-ENT,Otolaryngology (ENT),Surgical,Ear nose and throat clinic and audiology,DOC-008,Ext. 314,Third Floor Block B,TRUE,FALSE,FALSE,TRUE,FALSE,Active
DEP-DERM,Dermatology & Skin Care,Clinical,Outpatient skin disease consultations and cryotherapy,DOC-004,Ext. 318,Third Floor Block A,TRUE,FALSE,FALSE,FALSE,FALSE,Active
DEP-NEURO,Neurology & Stroke Care,Clinical,Neurological diagnostics and inpatient stroke monitoring,DOC-001,Ext. 322,Second Floor Block B,TRUE,TRUE,FALSE,TRUE,FALSE,Active
DEP-CARD,Cardiology & Vascular,Clinical,Duplicate code test row,DOC-001,Ext. 301,Second Floor,TRUE,FALSE,FALSE,TRUE,FALSE,Active
DEP-INVALID,,InvalidType,,UNKNOWN-999,Ext. 999,Nowhere,NOT_BOOL,FALSE,FALSE,FALSE,FALSE,InvalidStatus`;
